string *bigtask1=({
    "/d/npc/bigtask/npc/jinlong",
    "/d/npc/bigtask/npc/konglong",
    "/d/npc/bigtask/npc/dapeng",
    "/d/npc/bigtask/npc/pig",
    "/d/npc/bigtask/npc/yeren",
    "/d/npc/bigtask/npc/ghost",
    "/d/npc/bigtask/npc/kuangmo",
    "/d/npc/bigtask/npc/snake",
    "/d/npc/bigtask/npc/zhuha",
    "/d/npc/bigtask/npc/snake2",
    "/d/npc/bigtask/npc/tiger",
    "/d/npc/bigtask/npc/monv",
    "/d/npc/bigtask/npc/nielong",
    "/d/npc/bigtask/npc/monkey",
    "/d/npc/bigtask/npc/gui",
    "/d/npc/bigtask/npc/bird",
    "/d/npc/bigtask/npc/bianfu",
    "/d/npc/bigtask/npc/chong",
    "/d/npc/bigtask/npc/snake3",
    "/d/npc/bigtask/npc/xuezhu",
    "/d/npc/bigtask/npc/shalong",
    "/d/npc/bigtask/npc/snake4",
    "/d/npc/bigtask/npc/jiu",
});

string *bigtask2=({
    "/d/npc/bigtask/obj/blade",
});

string *bigtask3 = ({
    "大雪山",
    "方寸山三星洞",
    "月宫",
    "南海普陀山",
    "阎罗地府",
    "盘丝洞",
    "将军府",
    "东海龙宫",
    "陷空山无底洞",
    "五庄观",
    "火云洞",
    "蜀山剑派",
    "大唐皇宫",
    "乌鸡国",
    "宝象国",
    "天竺国",
    "女儿国",
    "玉华县",
});
string *bigtask4=({
    "/d/npc/bigtask/quest/stone1",
    "/d/npc/bigtask/quest/stone2",
    "/d/npc/bigtask/quest/stone3",
    "/d/npc/bigtask/quest/stone4",
    "/d/npc/bigtask/quest/stone5",
    "/d/npc/bigtask/quest/jade1",
    "/d/npc/bigtask/quest/jade2",
    "/d/npc/bigtask/quest/jade3",
    "/d/npc/bigtask/quest/jade4",
    "/d/npc/bigtask/quest/star1",
    "/d/npc/bigtask/quest/star2",
    "/d/npc/bigtask/quest/star3",
    "/d/npc/bigtask/quest/star4",
    "/d/npc/bigtask/quest/star5",
    "/d/npc/bigtask/quest/star6",
    "/d/npc/bigtask/quest/star7",
    "/d/npc/bigtask/quest/stone21",
    "/d/npc/bigtask/quest/stone22",
    "/d/npc/bigtask/quest/stone23",
    "/d/npc/bigtask/quest/stone24",
    "/d/npc/bigtask/quest/stone25",
    "/d/npc/bigtask/quest/stone26",
});

