mapping Npcs = ([
"卢生": ({"lu sheng","/d/changan/npc/lusheng",}),
"铁算盘": ({"tie suanpan","/d/changan/npc/tiesp",}),
"蒲牢": ({"pu lao","/d/sea/npc/long1",}),
"神鹰使者": ({"shenying shizhe","/d/xueshan/npc/shenying-shizhe",}),
"老头": ({"officer","/d/changan/officer",}),
"黄飞虎": ({"huang feihu","/d/changan/npc/huang",}),
"守城武将": ({"wu jiang","/d/city/npc/wujiang",}),
"小兵": ({"xiao bing","/d/city/npc/bing",}),
"蚣蝮": ({"gong fu","/d/sea/npc/long7",}),
"小枚儿": ({"xiao amy","/d/wiz/flower/npc/flowerseller",}),
"李定": ({"qiaofu","/d/changan/npc/qiaofu",}),
"张梢": ({"fisher","/d/changan/npc/fisher",}),
//city:
"癞头和尚": ({"laitou heshang","/d/penglai/npc/laitou",}),
"和尚": ({"heshang","/d/nanhai/npc/bonze",}),
"疥顶小僧": ({"jieding xiaoseng","/d/city/npc/jieding",}),
"小小千寻": ({"xxqianxun","/d/city/npc/vikee",}),
"冰谷巡使": ({"xunshi","/d/xueshan/npc/xunshi-out",}),
"魏录齐": ({"wei luqi","/d/city/npc/laowei",}),
"老头": ({"lao tou","/d/city/npc/laotou",}),
"杨中顺": ({"yang zhongshun","/d/city/npc/yang",}),
"不知和尚": ({"buzhi heshang","/d/city/npc/heshang",}),
"守城武将": ({"wu jiang","/d/city/npc/wujiang",}),
"小兵": ({"xiao bing","/d/city/npc/bing",}),
"老害虫": ({"xifuhui boss","/d/city/npc/boss",}),
"二姨太": ({"er yitai","/d/city/npc/eryi",}),
"姚富贵": ({"yao fugui","/d/city/npc/xiaoliu",}),
"范九席": ({"fan jiuxi","/quest/biao/npc",}),
"范青屏": ({"fan qingping","/d/city/npc/fan",}),
"武馆弟子": ({"wuguan dizi","/d/city/npc/dizi",}),
"范芦平": ({"fan luping","/d/city/npc/jiaotou",}),
"袁天罡": ({"yuan tiangang","/d/city/npc/yuantiangang",}),
"精灵": ({"spirit","/d/wiz/npc/spirit",}),
"公孙大娘": ({"gongsun daniang","/d/city/npc/gongsun",}),
"打手": ({"da shou","/d/city/npc/fei1",}),
"打手": ({"da shou","/d/city/npc/fei2",}),
"花忍": ({"hua ren","/d/city/npc/tangzhu1",}),
"雾渊道长": ({"wuyuan daozhang","/d/city/npc/daozhang",}),
"小道士": ({"xiao dao","/d/lingtai/npc/xiao",}),
"游侠儿": ({"youxia er","/d/city/npc/youxia",}),
"男孩": ({"boy","/d/city/npc/boy",}),
"妇人": ({"woman","/d/city/npc/woman",}),
"穷汉": ({"qiong han","/d/qujing/wudidong/npc/bianfu",}),
"大老鼠": ({"rat","/d/city/npc/rat",}),
"小痞子": ({"xiao pizi","/d/city/npc/xiaopizi",}),
"李玉娘": ({"li yuniang","/d/city/npc/liyu",}),
"驼背老人": ({"old man","/d/eastway/npc/man",}),
"女孩": ({"girl","/d/city/npc/girl",}),
"老孙": ({"lao sun","/d/city/npc/laosun",}),
"丰永贵": ({"feng yonggui","/d/city/npc/feng",}),
"纪嫣然": ({"ji yanran","/d/city/npc/family",}),
"千里眼": ({"qianli yan","/d/ourhome/npc/bigeye",}),
"店小二": ({"xiao er","/d/city/npc/xiaoer",}),
"礼物使者": ({"shizhe","/d/wiz/npc/liwu",}),
"大和尚": ({"monk","/d/city/npc/sengren1",}),
"高秀才": ({"xiucai","/d/city/npc/xiucai1",}),
"胖秀才": ({"xiucai","/d/city/npc/xiucai2",}),
"贺知章": ({"he zhizhang","/d/city/npc/xiucai4",}),
"法明长老": ({"faming zhanglao","/d/city/npc/faming",}),
"往事如风": ({"wangshi rufeng","/d/city/npc/age",}),
"董朴升": ({"dong pusheng","/d/city/npc/pablo",}),
"酸秀才": ({"suan xiucai","/d/city/npc/suanxiucai",}),
"茶博士": ({"cha boshi","/d/city/npc/teawaiter",}),
"庙祝": ({"miao zhu","/d/city/npc/keeper",}),
"张果老": ({"zhang guolao","/d/qujing/wuzhuang/npc/zhangguolao",}),
"李白": ({"li bai","/d/city/npc/libai",}),
"白衣秀士": ({"xiu shi","/d/city/npc/xiushi",}),
"袁守诚": ({"yuan shoucheng","/d/city/npc/yuanshouchen",}),
"孔方兄": ({"kong fang","/d/city/npc/bookseller",}),
"萧萧": ({"xiao xiao","/d/city/npc/xiaoxiao",}),
"小流氓": ({"xiao liumang","/d/city/npc/liumang",}),
"瘦老头": ({"lao tou","/d/city/npc/thief",}),
"赵老板": ({"boss daoluan","/d/city/npc/zhaodaoluan",}),
"朱老板": ({"boss dachang","/d/city/npc/zhudachang",}),
"铁算盘": ({"tie suanpan","/d/city/npc/tiesuanpan",}),
//huanggong:
"守城官兵": ({"guan bing","/d/wiz/npc/boss_guard",}),
"金甲卫士": ({"wei shi","/d/huanggong/npc/weishi",}),
//death:
"阎罗王": ({"yanluo wang","/d/death/npc/yanluowang",}),
"黄衣童子": ({"tongzi","/d/death/npc/tong2",}),
"紫衣童子": ({"tongzi","/d/death/npc/tong1",}),
"勾司人": ({"gousi ren","/d/death/npc/gousiren",}),
"秦广王": ({"qinguang wang","/d/death/npc/qinguangwang",}),
"楚江王": ({"chujiang wang","/d/death/npc/chujiangwang",}),
"宋帝王": ({"songdi wang","/d/death/npc/songdiwang",}),
"仵官王": ({"chuguan wang","/d/death/npc/chuguanwang",}),
"平等王": ({"pingdeng wang","/d/death/npc/pingdengwang",}),
"泰山王": ({"taishan wang","/d/death/npc/taishanwang",}),
"都市王": ({"dushi wang","/d/death/npc/dushiwang",}),
"卞城王": ({"biancheng wang","/d/death/npc/bianchengwang",}),
"轮转王": ({"lunzhuan wang","/d/death/npc/lunzhuanwang",}),
"白无常": ({"bai wuchang","/d/death/npc/baiwuchang",}),
"黑无常": ({"hei wuchang","/d/death/npc/heiwuchang",}),
"神荼": ({"shen tu","/d/death/npc/shentu",}),
"郁垒": ({"yu lei","/d/death/npc/yulei",}),
"马面鬼": ({"mamian gui","/d/death/npc/mamian",}),
"牛头鬼": ({"niutou gui","/d/death/npc/niutou",}),
"打更鬼": ({"dageng gui","/d/death/npc/genggui",}),
"冥王": ({"ming wang","/d/death/npc/mingwang",}),
"王方平": ({"wang fangping","/d/death/npc/wangfangping",}),
"阴长生": ({"yin changsheng","/d/death/npc/yinchangsheng",}),
"桥梁使者": ({"bridge guard","/d/death/npc/shizhe",}),
"崔珏": ({"cui jue","/d/death/npc/pang",}),
//"钟馗": ({"zhong kui","/quest/抓鬼/npc/kui",}),
"地藏王菩萨": ({"dizang pusa","/d/death/npc/dizhang",}),
"断足鬼": ({"duanzu gui","/d/death/npc/duanzhu",}),
//dntg/bmw:
"监副": ({"jian fu","/d/dntg/bmw/npc/jianfu",}),
"监丞": ({"jian cheng","/d/dntg/bmw/npc/jiancheng",}),
"典簿": ({"dian bu","/d/dntg/bmw/npc/dianbu",}),
"神兵": ({"shen bing","/d/dntg/bmw/npc/shenbing",}),
"小马崽": ({"ma zai","/d/dntg/bmw/npc/horsebaby",}),
"监官": ({"jian guan","/d/dntg/bmw/npc/jianguan",}),
//dntg/hgs:
"老头": ({"laotou","/d/dntg/hgs/npc/laotou",}),
"瓜瓜": ({"star ggggg","/d/dntg/sky/stars/ggggg",}),
"鹚鹄": ({"ci hu","/d/dntg/hgs/npc/cihu",}),
"花鸨": ({"hua bao","/d/dntg/hgs/npc/huabao",}),
"水蛇": ({"shui she","/d/dntg/hgs/npc/shuishe",}),
"鱼儿": ({"fish","/d/dntg/hgs/npc/fish",}),
"小女孩": ({"kid","/d/dntg/hgs/npc/kid",}),
"大马猴": ({"mahou","/d/dntg/hgs/npc/monkey2",}),
"小猴子": ({"xiao houzi","/d/dntg/hgs/npc/monkey1",}),
"蓝图郁": ({"lan tuyu","/d/dntg/hgs/npc/xiucai",}),
"阿七婆": ({"aqi po","/d/dntg/hgs/npc/aqi",}),
"芭将军": ({"ba jiangjun","/d/dntg/hgs/npc/ba",}),
"麻雀": ({"maque","/d/dntg/hgs/npc/maque",}),
"花匠": ({"hua jiang","/d/dntg/hgs/npc/gardener",}),
"东方博玉": ({"dongfang boyu","/d/dntg/hgs/npc/dongfang",}),
"东方英": ({"dongfang ying","/d/dntg/hgs/npc/dongfangying",}),
"东方小二姐": ({"dongfang sister","/d/dntg/hgs/npc/dongfanger",}),
"东方聪": ({"dongfang cong","/d/dntg/hgs/npc/dongfangcong",}),
"武馆弟子": ({"wuguan dizi","/d/dntg/hgs/npc/dizi",}),
"老齐": ({"guard","/d/dntg/hgs/npc/guard",}),
"竹小弟": ({"bamboo kid","/d/dntg/hgs/npc/zhu2",}),
"竹老大": ({"bamboo man","/d/dntg/hgs/npc/zhu1",}),
"妇人": ({"woman","/d/dntg/hgs/npc/woman",}),
"风间准": ({"star fjz","/d/dntg/sky/stars/fjz",}),
"吴本钱": ({"wu benqian","/d/dntg/hgs/npc/wu",}),
"傲来国武士": ({"wu shi","/d/dntg/hgs/npc/wushi",}),
"崩将军": ({"beng jiangjun","/d/dntg/hgs/npc/beng",}),
"壮汉": ({"man","/d/dntg/hgs/npc/man",}),
"小道童": ({"star kuer","/d/dntg/sky/stars/kuer",}),
"马元帅": ({"ma yuanshuai","/d/dntg/hgs/npc/ma-yuanshuai",}),
"流元帅": ({"liu yuanshuai","/d/dntg/hgs/npc/liu-yuanshuai",}),
"老母鸡": ({"old hen","/d/dntg/hgs/npc/muji",}),
"顺风耳": ({"shunfeng er","/d/ourhome/npc/longear",}),
"穆小乙": ({"xiao yi","/d/city/npc/xiaoyi",}),
"小男孩": ({"kid","/d/dntg/hgs/npc/kid1",}),
"店小二": ({"xiao er","/d/dntg/hgs/npc/xiaoer",}),
"江湖艺人": ({"yiren","/d/dntg/hgs/npc/yiren",}),
"偏将": ({"pian jiang","/d/dntg/hgs/npc/pianjiang",}),
"禁军教头": ({"jinjun jiaotou","/d/dntg/hgs/npc/jiaotou",}),
//dntg/lijing:
//dntg/pantao:
"素衣仙女": ({"suyi xiannu","/d/dntg/pantao/npc/xiannu7",}),
"皂衣仙女": ({"zaoyi xiannu","/d/dntg/pantao/npc/xiannu6",}),
"青衣仙女": ({"qingyi xiannu","/d/dntg/pantao/npc/xiannu5",}),
"红衣仙女": ({"hongyi xiannu","/d/dntg/pantao/npc/xiannu4",}),
"绿衣仙女": ({"luyi xiannu","/d/dntg/pantao/npc/xiannu3",}),
"紫衣仙女": ({"ziyi xiannu","/d/dntg/pantao/npc/xiannu2",}),
"黄衣仙女": ({"huangyi xiannu","/d/dntg/pantao/npc/xiannu1",}),
"施肥力士": ({"li shi","/d/dntg/pantao/npc/lishi6",}),
"培土力士": ({"li shi","/d/dntg/pantao/npc/lishi7",}),
"打扫力士": ({"li shi","/d/dntg/pantao/npc/lishi4",}),
"剪枝力士": ({"li shi","/d/dntg/pantao/npc/lishi5",}),
"修桃力士": ({"li shi","/d/dntg/pantao/npc/lishi3",}),
"锄树力士": ({"li shi","/d/dntg/pantao/npc/lishi1",}),
"运水力士": ({"li shi","/d/dntg/pantao/npc/lishi2",}),
"土地": ({"tu di","/d/dntg/pantao/npc/tudi",}),
//dntg/sky:
"护宫卫士": ({"wei shi","/d/dntg/sky/npc/hgweishi",}),
"魔礼海": ({"moli hai","/d/dntg/sky/npc/moli-hai",}),
"织女": ({"zhi nu","/d/dntg/sky/npc/zhinu",}),
"天兵": ({"tian bing","/d/dntg/sky/npc/tian-bing",}),
"佑圣真君": ({"yousheng zhenjun","/d/dntg/sky/npc/youshengzhenjun",}),
"陶昕岗": ({"tao xin gang","/d/dntg/sky/npc/tianding8",}),
"张学松": ({"zhang xue song","/d/dntg/sky/npc/tianding7",}),
"辛酒泉": ({"xin jiu quan","/d/dntg/sky/npc/tianding6",}),
"邓国岩": ({"deng guo yan","/d/dntg/sky/npc/tianding5",}),
"时值功曹": ({"shizhi gongcao","/d/dntg/sky/npc/winter-gongcao",}),
"电母": ({"dian mu","/d/dntg/sky/npc/dianmu",}),
"雷公": ({"lei gong","/d/dntg/sky/npc/leigong",}),
"云童": ({"yun tong","/d/dntg/sky/npc/yuntong",}),
"风婆": ({"feng po","/d/dntg/sky/npc/fengpo",}),
"年值功曹": ({"nianzhi gongcao","/d/dntg/sky/npc/spring-gongcao",}),
"日值功曹": ({"rizhi gongcao","/d/dntg/sky/npc/autumn-gongcao",}),
"月值功曹": ({"yuezhi gongcao","/d/dntg/sky/npc/summer-gongcao",}),
"毕岩庭": ({"bi yan ting","/d/dntg/sky/npc/tianding4",}),
"苟余阳": ({"gou yun yang","/d/dntg/sky/npc/tianding3",}),
"刘晚旗": ({"liu wan qi","/d/dntg/sky/npc/tianding2",}),
"庞进阁": ({"pang jin ge","/d/dntg/sky/npc/tianding1",}),
"魔礼青": ({"moli qing","/d/dntg/sky/npc/moli-qing",}),
"武曲星君": ({"wuqu xingjun","/d/dntg/sky/npc/wuquxingjun",}),
"玉皇大帝": ({"yuhuang dadi","/d/dntg/sky/npc/yuhuang",}),
"魔礼红": ({"moli hong","/d/dntg/sky/npc/moli-hong",}),
"牛郎": ({"niu lang","/d/dntg/sky/npc/niulang",}),
"翊圣真君": ({"yisheng zhenjun","/d/dntg/sky/npc/yishengzhenjun",}),
"魔礼寿": ({"moli shou","/d/dntg/sky/npc/moli-shou",}),
"浪翻云": ({"star lfy","/d/dntg/sky/stars/lfy",}),
//dntg/yaochi:
"赤脚大仙": ({"chijiao daxian","/d/dntg/yaochi/npc/chijiao",}),
"金甲卫士": ({"jinjia weishi","/d/dntg/yaochi/npc/guard",}),
"造酒仙官": ({"zaojiu xianguan","/d/dntg/yaochi/npc/xianguan",}),
//eastway:
"浣衣女": ({"girl","/d/eastway/npc/girl",}),
"游客": ({"you ke","/d/eastway/npc/youke",}),
"老妇人": ({"fu ren","/d/eastway/npc/furen",}),
"武将": ({"wu jiang","/d/eastway/npc/wujiang",}),
"小兵": ({"xiao bing","/d/eastway/npc/bing",}),
"二姨太": ({"er yitai","/d/eastway/npc/bosswife",}),
"老板": ({"boss","/d/eastway/npc/petboss",}),
"孙秀才": ({"xiucai","/d/eastway/npc/xiucai",}),
"戴文重": ({"dai wenzhong","/d/eastway/npc/dai",}),
"路人": ({"luren","/d/eastway/npc/luren",}),
"僧人": ({"seng ren","/d/eastway/npc/sengren",}),
//gao:
"高员外": ({"gao yuanwai","/d/gao/npc/gao",}),
"小丫环": ({"yahuan","/d/gao/npc/yahuan2",}),
"高正": ({"gao zheng","/d/gao/npc/guanjia",}),
"高才": ({"gao cai","/d/gao/npc/huoji",}),
"高小姐": ({"gao xiaojie","/d/gao/npc/gaoxiaojie",}),
"匡文正": ({"kuang wenzheng","/d/gao/npc/teacher",}),
"小学童": ({"xuetong","/d/gao/npc/kid",}),
"土匪": ({"bandit","/d/gao/npc/tufei",}),
"土匪头目": ({"bandit leader","/d/gao/npc/guard",}),
"老妈子": ({"laomaz","/d/gao/npc/washer",}),
"老李头": ({"lao li","/d/gao/npc/laoli",}),
"小学徒": ({"xuetu","/d/gao/npc/xuetu",}),
"夏鹏展": ({"xia pengzhan","/d/gao/npc/head",}),
"小贩": ({"xiaofan","/d/gao/npc/xiaofan",}),
"高婆": ({"gao po","/d/gao/npc/gaopo",}),
"丫环": ({"yahuan","/d/gao/npc/yahuan1",}),
"家丁": ({"jiading","/d/gao/npc/jiading",}),
"王掌柜": ({"wang zhanggui","/d/gao/npc/wang",}),
"酒客": ({"jiuke","/d/gao/npc/jiuke",}),
"老余头": ({"laoyu","/d/gao/npc/laoyu",}),
"农夫": ({"farmer","/d/gao/npc/farmer",}),
"吴文": ({"wu wen","/d/gao/npc/cunzhang",}),
"胖嫂": ({"pang sao","/d/gao/npc/pangsao",}),
//jjf:
"李元吉": ({"li yuanji","/d/jjf/npc/liyuanji",}),
"李建成": ({"li jiancheng","/d/jjf/npc/lijiancheng",}),
"亲兵": ({"qin bing","/d/jjf/npc/qinbing-qi",}),
"亲兵": ({"qin bing","/d/jjf/npc/qinbing-jian",}),
"司马安国": ({"fu jiang","/d/jjf/npc/fujiang",}),
"程咬金": ({"cheng yaojin","/d/jjf/npc/chengyaojin",}),
"盘古": ({"pan gu","/d/jjf/npc/pangu",}),
"白发老人": ({"lao ren","/d/jjf/npc/baifalaoren",}),
"尉迟恭": ({"yuchi gong","/d/jjf/npc/yuchigong",}),
"小童": ({"xiao tong","/d/jjf/npc/xiaotong",}),
"家将": ({"jia jiang","/d/jjf/npc/jiajiang",}),
"秦琼": ({"qin qiong","/d/jjf/npc/qinqiong",}),
"秦平": ({"qin ping","/d/jjf/npc/qinping",}),
"罗成": ({"luo cheng","/d/jjf/npc/luocheng",}),
"罗春": ({"luo chun","/d/jjf/npc/luochun",}),
"秦安": ({"qin an","/d/jjf/npc/qinan",}),
"校尉": ({"xiao wei","/d/jjf/npc/guard",}),
"秦富": ({"qin fu","/d/jjf/npc/qinfu",}),
//jz:
"伙计": ({"huoji","/d/jz/npc/yang",}),
"刘寿雄": ({"yayi","/d/jz/npc/yayi",}),
"说书的": ({"man","/d/jz/npc/people",}),
"凌汤圆": ({"ling","/d/jz/npc/ling",}),
"王大嫂": ({"wang dasao","/d/jz/npc/wang",}),
"守城武将": ({"wu jiang","/d/city/npc/wujiang",}),
"卖鱼竿的": ({"seller","/d/jz/npc/waiter",}),
"老者": ({"old man","/d/jz/npc/laozhe",}),
"殷温娇": ({"yin wenjiao","/d/jz/npc/yin",}),
"荷花": ({"he hua","/d/jz/npc/hehua",}),
"法明长老": ({"faming zhanglao","/d/jz/npc/faming",}),
"王小二": ({"wang","/d/jz/npc/wang2",}),
//kaifeng:
"小童": ({"xiao tong","/d/kaifeng/npc/xiaotong",}),
"禹王爷": ({"yuwang ye","/d/kaifeng/npc/ye",}),
"禹王卒": ({"yuwang zu","/d/kaifeng/npc/zu",}),
"丫环": ({"ya huan","/d/kaifeng/npc/yahuan",}),
"杨老板": ({"yang laoban","/d/kaifeng/npc/yang",}),
"香兰": ({"xiang lan","/d/kaifeng/npc/xianglan",}),
"伺官": ({"si guan","/d/kaifeng/npc/siguan",}),
"宫卫": ({"gong wei","/d/kaifeng/npc/gongwei",}),
"猪兵": ({"zhu bing","/d/kaifeng/npc/zhubing",}),
"猪八戒": ({"zhu bajie","/d/kaifeng/npc/zhubajie",}),
"海老板": ({"hai laoban","/d/kaifeng/npc/hai",}),
"道士": ({"dao shi","/d/kaifeng/npc/people",}),
"殷温娇": ({"yin wenjiao","/d/kaifeng/npc/yin",}),
"马官": ({"ma guan","/d/kaifeng/npc/maguan",}),
"相婆": ({"xiang po","/d/kaifeng/npc/xpo",}),
"陈光蕊": ({"chen guangrui","/d/kaifeng/npc/chen",}),
"胡敬德": ({"hu jingde","/d/kaifeng/npc/hu",}),
"徐老板": ({"xu laoban","/d/kaifeng/npc/xu",}),
"茶娘子": ({"chaniang zi","/d/kaifeng/npc/chaniang",}),
"兵士": ({"bing shi","/d/kaifeng/npc/bing",}),
"守城武将": ({"wu jiang","/d/kaifeng/npc/wujiang",}),
"相公": ({"xiang gong","/d/kaifeng/npc/xgong",}),
//lingtai:
"青狮老魔": ({"qingshi laomo","/d/xueshan/npc/qingshi-laomo",}),
"樵夫": ({"qiao fu","/d/lingtai/npc/qiaofu",}),
"菩提祖师": ({"master puti","/d/lingtai/npc/puti",}),
"砍柴道士": ({"taoist","/d/lingtai/npc/kancai",}),
"云阳真人": ({"master yunyang","/d/lingtai/npc/yunyang",}),
"小道士": ({"xiao dao","/d/lingtai/npc/xiao",}),
"广羲子": ({"guang xizi","/d/lingtai/npc/guangxi",}),
"老道士": ({"laodao","/d/lingtai/npc/laodao",}),
"慧琉": ({"hui liu","/d/lingtai/npc/huiliu",}),
"慧纲": ({"hui gang","/d/lingtai/npc/huigang",}),
"云清": ({"yun qing","/d/lingtai/npc/yunqing",}),
"皤不分": ({"bo bufen","/d/lingtai/npc/shixong",}),
"广筠子": ({"guang yunzi","/d/lingtai/npc/guangyun",}),
"晚风": ({"wan feng","/d/lingtai/npc/wanfeng",}),
"云静": ({"yun jing","/d/lingtai/npc/yunjing",}),
"扫地小童": ({"xiao tong","/d/lingtai/npc/xiaodao",}),
"梅花鹿": ({"meihua lu","/d/sea/npc/beast/beast1",}),
"张道陵": ({"zhang daoling","/d/lingtai/npc/zhangdaoling",}),
"晨月": ({"chen yue","/d/lingtai/npc/yingke",}),
//luoyang:
"茶博士": ({"waiter","/d/luoyang/npc/teawater",}),
"武圣关公": ({"guan gong","/d/luoyang/npc/guan",}),
"弟子": ({"dizi","/d/luoyang/npc/dizi",}),
"赵铁拳": ({"zhao tiequan","/d/luoyang/npc/jiaotou",}),
//meishan:
"李焕章": ({"li huanzhang","/d/meishan/npc/li",}),
"姚公麟": ({"yao gonglin","/d/meishan/npc/yao",}),
"二妞": ({"er niu","/d/meishan/npc/girl",}),
"张伯时": ({"zhang boshi","/d/meishan/npc/zhang",}),
"张顺": ({"zhang shun","/d/meishan/npc/zhangsun",}),
"康安裕": ({"kang anyu","/d/meishan/npc/kang",}),
"郭申": ({"guo shen","/d/meishan/npc/guo",}),
"直健": ({"zhi jian","/d/meishan/npc/zhi",}),
"旅客": ({"traveller","/d/meishan/npc/luke",}),
"烧香老太太": ({"lao taitai","/d/meishan/npc/laotai",}),
"庙祝": ({"miao zhu","/d/meishan/npc/miaozhu",}),
"渔姑": ({"yu gu","/d/meishan/npc/fefisher",}),
"渔翁": ({"yu weng","/d/meishan/npc/fisher",}),
//moon:
"轿夫头": ({"jiaofu tou","/d/moon/npc/jftou",}),
"轿夫": ({"jiaofu","/d/moon/npc/jiaofu",}),
"唢呐手": ({"suona shou","/d/moon/npc/snshou",}),
"锣鼓手": ({"luogu shou","/d/moon/npc/lgshou",}),
"月下老人": ({"yuexia laoren","/d/moon/npc/yuelao",}),
"月奴": ({"yue nu","/d/moon/npc/yuenu",}),
"小钻风": ({"xiao zuanfeng","/d/xueshan/npc/xiaozuanfeng",}),
"蝶衣": ({"butterfly","/d/moon/npc/fairy",}),
"菊影": ({"shade","/d/moon/npc/fairy1",}),
"西王母": ({"xi wangmu","/d/moon/npc/xiwangmu1",}),
"玉兔": ({"yu tu","/d/moon/npc/yutu",}),
"桂树": ({"gui shu","/d/moon/npc/guishu",}),
"吴刚": ({"wu gang","/d/moon/npc/wugang",}),
"豌豆花": ({"girl","/d/moon/npc/girl",}),
"麻姑": ({"magu","/d/moon/npc/magu",}),
"痴梦仙姑": ({"chi meng","/d/moon/npc/chimeng",}),
"锄药": ({"chu yao","/d/moon/npc/fairy4",}),
"抱琴": ({"bao qin","/d/moon/npc/fairy3",}),
"茗烟": ({"ming yan","/d/moon/npc/fairy2",}),
"女娲娘娘": ({"nu wa","/d/moon/npc/nuwa",}),
"扫红": ({"shao hong","/d/moon/npc/fairy5",}),
"嫦娥": ({"chang e","/d/moon/npc/change",}),
//nanhai:
"掌厨僧": ({"zhangchu seng","/d/nanhai/npc/zhangchu",}),
"黑熊怪": ({"bear monster","/d/nanhai/npc/bear-monster",}),
"剃度僧": ({"tidu seng","/d/nanhai/npc/tidu",}),
"小沙弥": ({"shami","/d/nanhai/npc/shami",}),
"游方行者": ({"xingzhe","/d/nanhai/npc/xingzhe",}),
"吕洞宾": ({"lu dongbin","/d/qujing/wuzhuang/npc/ludongbin",}),
"惠岸行者": ({"huian xingzhe","/d/nanhai/npc/huian",}),
"知客僧": ({"zhike seng","/d/nanhai/npc/zhike",}),
"观音菩萨": ({"guanyin pusa","/d/nanhai/npc/guanyin",}),
"净瓶使者": ({"shizhe","/d/nanhai/npc/shizhe",}),
"善财童子": ({"shancai tongzi","/d/nanhai/npc/shancai",}),
"掌禅僧": ({"zhangchan seng","/d/nanhai/npc/zhangchan",}),
//pansi:
"香香": ({"xiang xiang","/d/pansi/npc/xiang",}),
"姬邑考": ({"ji yikao","/d/pansi/npc/jikao",}),
"金灵圣母": ({"jinling shengmu","/d/pansi/npc/shengmu",}),
"白晶晶": ({"bai jingjing","/d/pansi/npc/bai",}),
"春三十娘": ({"chun sanshiniang","/d/pansi/npc/niang",}),
//penglai:
"禄星": ({"lu xing","/d/penglai/npc/luxing",}),
"福星": ({"fu xing","/d/penglai/npc/fuxing",}),
"寿星": ({"shou xing","/d/penglai/npc/shouxing",}),
"白猿": ({"bai yuan","/d/penglai/npc/baiyuan",}),
"小童": ({"xiao tong","/d/baihuagu/npc/xiaotong",}),
"百花仙子": ({"baihua xianzi","/d/penglai/npc/baihua-xianzi",}),
//sea:
"金鳌力士": ({"li shi","/d/sea/npc/lishi",}),
"花皮龙": ({"dragon","/d/sea/npc/beast",}),
"霸下": ({"ba xia","/d/sea/npc/long4",}),
"小水母": ({"kid","/d/sea/npc/kid3",}),
"小螃蟹": ({"kid","/d/sea/npc/kid1",}),
"小虾米": ({"kid","/d/sea/npc/kid2",}),
"巡海夜叉": ({"ye cha","/d/sea/npc/yecha",}),
"鲻太尉": ({"zi taiwei","/d/sea/npc/zitaiwei",}),
"鲭都司": ({"qing dusi","/d/sea/npc/qingdusi",}),
"宫娥": ({"gong e","/d/sea/npc/gonge",}),
"金睛蛟": ({"jiao","/d/sea/npc/beast3",}),
"花头鼋": ({"yuan","/d/sea/npc/beast2",}),
"虎齿龟": ({"gui","/d/sea/npc/beast1",}),
"鳊提督": ({"bian tidu","/d/sea/npc/biantidu",}),
"鲤总兵": ({"li zongbing","/d/sea/npc/lizongbing",}),
"鲸无敌": ({"jing wudi","/d/sea/npc/jing",}),
"龟八斗": ({"gui badou","/d/sea/npc/gui",}),
"龙婆": ({"long po","/d/sea/npc/longpo",}),
"椒图": ({"shu tu","/d/sea/npc/long9",}),
"敖广": ({"ao guang","/d/sea/npc/longwang",}),
"虾兵": ({"xia bing","/d/sea/npc/soldier1",}),
"绿背鲨": ({"shark","/d/sea/npc/shark",}),
"黄贝宫女": ({"gong nu","/d/sea/npc/beinu",}),
"贝嫂": ({"beisao","/d/sea/npc/beisao",}),
"宫女": ({"gongnu","/d/sea/npc/gongnu",}),
"龙女": ({"long nu","/d/sea/npc/longnu",}),
"螭吻": ({"chi wen","/d/sea/npc/long5",}),
"鳅婆": ({"qiupo","/d/sea/npc/qiupo",}),
"蟹将": ({"xie jiang","/d/sea/npc/soldier2",}),
"饕餮": ({"tao tie","/d/sea/npc/long6",}),
"睚眦": ({"ya zi","/d/sea/npc/long3",}),
"龙表弟": ({"long biaodi","/d/sea/npc/biaodi",}),
"狴犴": ({"bi an","/d/sea/npc/long2",}),
"龙少爷": ({"long shaoye","/d/sea/npc/longshao",}),
//shushan:
"李逍遥": ({"li xiaoyao","/d/shushan/npc/lxy",}),
"剑童": ({"jian tong","/d/shushan/npc/jiantong",}),
"知客剑童": ({"zhike jiantong","/d/shushan/npc/zhike",}),
"怪老道": ({"guai laodao","/d/shushan/npc/laodao",}),
"守山剑童": ({"jian tong","/d/shushan/npc/guard",}),
"醉道士": ({"zui daoshi","/d/shushan/npc/zuidao",}),
"清风": ({"qing feng","/d/shushan/npc/qingfeng",}),
//westway:
"青髯老人": ({"lao ren","/d/westway/npc/laoren",}),
"特处士": ({"te chushi","/d/westway/npc/niu",}),
"寅将军": ({"yin jiangjun","/d/westway/npc/yin",}),
"熊山君": ({"xiong shanjun","/d/westway/npc/xiong",}),
"摊贩": ({"tan fan","/d/westway/npc/tanfan",}),
"急如火": ({"jiru huo","/d/qujing/kusong/npc/jiruhuo",}),
"边关守将": ({"wu jiang","/d/westway/npc/wujiang",}),
//xueshan:
"乌鸦先生": ({"wuya xiansheng","/d/xueshan/npc/wuya-guai",}),
"孔雀公主": ({"kongque gongzhu","/d/xueshan/npc/kongque-gongzhu",}),
"孔雀": ({"kong que","/d/xueshan/npc/ride1",}),
"凤凰": ({"feng huang","/d/xueshan/npc/ride2",}),
"黄雀侍儿": ({"huangque shier","/d/xueshan/npc/huangque-shier",}),
"白象尊者": ({"baixiang zunzhe","/d/xueshan/npc/baixiang-zunzhe",}),
"秃鹰尊者": ({"tuying zunzhe","/d/xueshan/npc/tuying-zunzhe",}),
"鹦鹉将军": ({"yingwu jiangjun","/d/xueshan/npc/yingwu-guai",}),
"冰谷巡使": ({"xunshi","/d/xueshan/npc/xunshi",}),
"雪山妖": ({"xushan yao","/d/xueshan/npc/xueshanyao",}),
"双尾蝎": ({"xiezi jing","/d/xueshan/npc/xiezi",}),
"蝴蝶": ({"hu die","/d/xueshan/npc/hudie",}),
"青蛇": ({"she","/d/xueshan/npc/chongzi",}),
"浣花": ({"huan hua","/d/xueshan/npc/huanhua",}),
"黄鹂侍儿": ({"shi er","/d/xueshan/npc/shier",}),
"大鹏明王": ({"dapeng mingwang","/d/xueshan/npc/dapeng",}),
//qujing/baotou:
"古怪刁钻": ({"guguai diaozuan","/d/qujing/baotou/npc/ggdz",}),
"刁钻古怪": ({"diaozuan guguai","/d/qujing/baotou/npc/dzgg",}),
//qujing/baoxiang:
"坊主": ({"fang zhu","/d/qujing/baoxiang/npc/fangzhu",}),
"宫兵": ({"gong bing","/d/qujing/baoxiang/npc/bing",}),
"宫妃": ({"gong fei","/d/qujing/baoxiang/npc/girl",}),
"女子": ({"nu zi","/d/qujing/baoxiang/npc/nuzi",}),
"老板": ({"laoban","/d/qujing/baoxiang/npc/laoban",}),
"锡匠": ({"xi jiang","/d/qujing/baoxiang/npc/xijiang",}),
"官人": ({"guan ren","/d/qujing/baoxiang/npc/people",}),
"国王": ({"guo wang","/d/qujing/baoxiang/npc/king",}),
"大使": ({"da shi","/d/qujing/baoxiang/npc/dashi",}),
"山妖": ({"shan yao","/d/qujing/baoxiang/npc/shanyao",}),
"黄袍怪": ({"huangpao guai","/d/qujing/baoxiang/npc/huangpao",}),
"百花羞": ({"baihua xiu","/d/qujing/baoxiang/npc/baihua",}),
//qujing/bibotan:
"古波儿西": ({"guboer xi","/d/qujing/bibotan/npc/bie",}),
"西波儿古": ({"xiboer gu","/d/qujing/bibotan/npc/gui",}),
"长腿虾婆": ({"xia po","/d/qujing/bibotan/npc/changtui",}),
"天波儿笑": ({"tianboer xiao","/d/qujing/bibotan/npc/niqiu",}),
"笑波儿天": ({"xiaoboer tian","/d/qujing/bibotan/npc/qingshan",}),
"赵二伯": ({"lie hu","/d/qujing/bibotan/npc/hunter",}),
"大肚虾婆": ({"xia po","/d/qujing/bibotan/npc/dadu",}),
"虾兵": ({"xia bing","/d/sea/npc/soldier1",}),
"万圣龙王": ({"wansheng longwang","/d/qujing/bibotan/npc/longwang",}),
"万圣公主": ({"wansheng gongzhu","/d/qujing/bibotan/npc/gongzhu",}),
"九头驸马": ({"jiutou fuma","/d/qujing/bibotan/npc/fuma",}),
"山妖": ({"shan yao","/d/qujing/bibotan/npc/shanyao",}),
"芦娘": ({"lu niang","/d/qujing/bibotan/npc/luniang",}),
"蟹将": ({"xie jiang","/d/sea/npc/soldier2",}),
"宫娥": ({"gong e","/d/sea/npc/gonge",}),
//qujing/biqiu:
"文官": ({"wen guan","/d/qujing/biqiu/npc/wenguan",}),
"宫妃": ({"gong fei","/d/qujing/biqiu/npc/girl",}),
"美后": ({"mei hou","/d/qujing/biqiu/npc/hou",}),
"库司库司": ({"kusi kusi","/d/qujing/biqiu/npc/kusikusi",}),
"坎都力": ({"kan duli","/d/qujing/biqiu/npc/kanduli",}),
"索哈娜": ({"suo hana","/d/qujing/biqiu/npc/suohana",}),
"拉苏律司": ({"lasu lusi","/d/qujing/biqiu/npc/lasulusi",}),
"路人": ({"lu ren","/d/qujing/biqiu/npc/people",}),
"小妖": ({"xiao yao","/d/qujing/biqiu/npc/yao",}),
"太监": ({"tai jian","/d/qujing/biqiu/npc/taijian",}),
"碧奴慕伊": ({"binu muyi","/d/qujing/biqiu/npc/binumuyi",}),
"国丈": ({"guo zhang","/d/qujing/biqiu/npc/guozhang",}),
"国王": ({"guo wang","/d/qujing/biqiu/npc/king",}),
//qujing/chechi:
"瘦和尚": ({"he shang","/d/qujing/chechi/npc/heshang",}),
"护宫卫士": ({"wei shi","/d/qujing/chechi/npc/weishi",}),
"金钗女": ({"jinchai nu","/d/qujing/chechi/npc/jinchai",}),
"戏子": ({"xi zi","/d/qujing/chechi/npc/xizi",}),
"小管家": ({"guan jia","/d/qujing/chechi/npc/xiaoguan",}),
"道士": ({"dao shi","/d/qujing/chechi/npc/daoshi",}),
"宫妃": ({"gong fei","/d/qujing/chechi/npc/girl",}),
"监斩官": ({"jianzhan guan","/d/qujing/chechi/npc/jz2",}),
"说书老": ({"shuoshu lao","/d/qujing/chechi/npc/shulao",}),
"灵宝道君": ({"lingbao daojun","/d/qujing/chechi/npc/lingbao",}),
"太上老君": ({"taishang laojun","/d/qujing/chechi/npc/taishang",}),
"元始天尊": ({"yuanshi tianzun","/d/qujing/chechi/npc/yuanshi",}),
"监斩官": ({"jianzhan guan","/d/qujing/chechi/npc/jz3",}),
"犸力大仙": ({"mali daxian","/d/qujing/chechi/npc/mali",}),
"豺力大仙": ({"chaili daxian","/d/qujing/chechi/npc/chaili",}),
"狈力大仙": ({"beili daxian","/d/qujing/chechi/npc/beili",}),
"狼力大仙": ({"langli daxian","/d/qujing/chechi/npc/langli",}),
"小官人": ({"xiao guanren","/d/qujing/chechi/npc/long",}),
"太监": ({"tai jian","/d/qujing/chechi/npc/taijian",}),
"酒保": ({"jiu bao","/d/qujing/chechi/npc/jiubao",}),
"监斩官": ({"jianzhan guan","/d/qujing/chechi/npc/jz1",}),
"国王": ({"guo wang","/d/qujing/chechi/npc/king",}),
"小贩": ({"xiao fan","/d/qujing/chechi/npc/people",}),
"道童": ({"dao tong","/d/qujing/chechi/npc/daotong",}),
"镖头": ({"biao tou","/d/city/npc/biaotou",}),
"花姐儿": ({"hua jieer","/d/qujing/chechi/npc/feng",}),
"五福道长": ({"dao zhang","/d/qujing/chechi/npc/daozhang",}),
"管家": ({"guan jia","/d/qujing/chechi/npc/daguan",}),
//qujing/dudi:
//qujing/fengxian:
"上官仪": ({"shangguan yi","/d/qujing/fengxian/npc/sg1",}),
"庙祝": ({"miao zhu","/d/qujing/fengxian/npc/miaozhu",}),
"饥民": ({"ji min","/d/qujing/fengxian/npc/people2",}),
"慈悲和尚": ({"cibei heshang","/d/qujing/fengxian/npc/monk",}),
"上官曲岸": ({"shangguan quan","/d/qujing/fengxian/npc/sg4",}),
"上官申尜": ({"shangguan shenga","/d/qujing/fengxian/npc/sg3",}),
"祭官": ({"ji guan","/d/qujing/fengxian/npc/jiguan",}),
"上官阿人": ({"shangguan aren","/d/qujing/fengxian/npc/sg2",}),
"布道法师": ({"budao fashi","/d/qujing/fengxian/npc/fashi",}),
//qujing/firemount:
"小贩": ({"vendor","/d/qujing/firemount/npc/vendor",}),
"芭蕉怪": ({"bajiao guai","/d/qujing/firemount/npc/bajiaoq",}),
"芭蕉怪": ({"bajiao guai","/d/qujing/firemount/npc/bajiaob",}),
"樵夫": ({"qiaofu","/d/qujing/firemount/npc/qiaofu",}),
"金猊": ({"jin ni","/d/sea/npc/long8",}),
"祝融氏": ({"zhurong shi","/d/qujing/firemount/npc/huoyun",}),
"老者": ({"oldman","/d/qujing/firemount/npc/oldman",}),
"小妖": ({"xiao yao","/d/qujing/firemount/npc/xiaoyao",}),
//qujing/guanyin:
"无名僧": ({"seng","/d/qujing/guanyin/npc/seng",}),
"妖怪": ({"yao guai","/d/qujing/guanyin/npc/guai1",}),
"广谋": ({"guangmou seng","/d/qujing/guanyin/npc/guangmou",}),
"金池上人": ({"lao yuanzhu","/d/qujing/guanyin/npc/yuanzhu",}),
"广智": ({"guangzhi seng","/d/qujing/guanyin/npc/guangzhi",}),
//qujing/heifeng:
"小和尚": ({"he shang","/d/qujing/heifeng/npc/welcome",}),
"凌虚子": ({"lingxu zi","/d/qujing/heifeng/npc/lingxu",}),
"白衣秀士": ({"baiyi xiushi","/d/qujing/heifeng/npc/baiyi",}),
"小妖": ({"xiao yao","/d/qujing/heifeng/npc/xiaoyao",}),
"黑熊怪": ({"hei xiong","/d/qujing/heifeng/npc/dahan",}),
"妖精": ({"yao jing","/d/qujing/heifeng/npc/yaojing",}),
"金池长老": ({"jin chi","/d/qujing/heifeng/npc/jinchi",}),
"念经和尚": ({"he shang","/d/qujing/heifeng/npc/monk1",}),
"广智": ({"guang zhi","/d/qujing/heifeng/npc/monk_gz",}),
"广谋": ({"guang mou","/d/qujing/heifeng/npc/monk_gm",}),
//qujing/huangfeng:
"守门妖": ({"shoumen yao","/d/qujing/huangfeng/npc/shoumenyao",}),
"王老板": ({"wang laoban","/d/qujing/huangfeng/npc/yaoboss",}),
"王安": ({"wang an","/d/qujing/huangfeng/npc/wangshan",}),
"猎户": ({"lie hu","/d/qujing/huangfeng/npc/people",}),
"黄风怪": ({"huangfeng guai","/d/qujing/huangfeng/npc/huangfengguai",}),
"迎客道人": ({"yingke daoren","/d/qujing/huangfeng/npc/ykdaoren",}),
"老者": ({"lao zhe","/d/qujing/huangfeng/npc/old",}),
"老村长": ({"cun zhang","/d/qujing/huangfeng/npc/cunzhang",}),
"小男孩": ({"kid","/d/qujing/huangfeng/npc/boykid",}),
"小女孩": ({"kid","/d/qujing/huangfeng/npc/girlkid",}),
"道人": ({"dao ren","/d/qujing/huangfeng/npc/daoren",}),
"王小二": ({"wang xiaoer","/d/qujing/huangfeng/npc/xiaoer",}),
"老者": ({"lao zhe","/d/qujing/huangfeng/npc/lingji1",}),
"黄风怪": ({"huangfeng guai","/d/qujing/huangfeng/npc/laoguai",}),
"虎先锋": ({"hu xianfeng","/d/qujing/huangfeng/npc/huxianfeng",}),
"王奶奶": ({"wang nainai","/d/qujing/huangfeng/npc/woman",}),
//qujing/jilei:
"玉面公主": ({"yumian gongzhu","/d/qujing/jilei/npc/yumian",}),
"牛魔王": ({"niumo wang","/d/qujing/jilei/npc/niumo",}),
"獾怪": ({"yao guai","/d/qujing/jilei/npc/yao",}),
//qujing/jindou:
"鹿怪": ({"yao guai","/d/qujing/jindou/npc/yao",}),
"独角兕大王": ({"dujiaosi dawang","/d/qujing/jindou/npc/dujiao",}),
//qujing/jingjiling:
"拂云叟": ({"fuyun sou","/d/qujing/jingjiling/npc/zhu",}),
"杏仙": ({"xing xian","/d/qujing/jingjiling/npc/xing",}),
"十八公": ({"shiba gong","/d/qujing/jingjiling/npc/song",}),
"赤身鬼使": ({"guard","/d/qujing/jingjiling/npc/guard",}),
"凌空子": ({"lingkong zi","/d/qujing/jingjiling/npc/hui",}),
"孤直公": ({"guzhi gong","/d/qujing/jingjiling/npc/bo",}),
//qujing/jinping:
"胖和尚": ({"he shang","/d/qujing/jinping/npc/monk",}),
"挑灯夫": ({"tiaodeng fu","/d/qujing/jinping/npc/people",}),
"灯官": ({"deng guan","/d/qujing/jinping/npc/dengguan",}),
"店主": ({"dian zhu","/d/qujing/jinping/npc/dianzhu",}),
"庙祝": ({"keeper","/d/qujing/jinping/npc/keeper",}),
"府官": ({"fu guan","/d/qujing/jinping/npc/guan",}),
"府令": ({"fu ling","/d/qujing/jinping/npc/fuling",}),
//qujing/jisaiguo:
"黄门官": ({"huangmen guan","/d/qujing/jisaiguo/npc/guan",}),
"柳妙手": ({"liu miaoshou","/d/qujing/jisaiguo/npc/doctor",}),
"祭赛国国王": ({"jisai guowang","/d/qujing/jisaiguo/npc/king",}),
"祭赛国武士": ({"wu shi","/d/qujing/jisaiguo/npc/guard",}),
"灞波儿奔": ({"baboer ben","/d/qujing/jisaiguo/npc/baben",}),
"奔波儿灞": ({"benboer ba","/d/qujing/jisaiguo/npc/benba",}),
"凌虚子": ({"lingxu zi","/d/qujing/jisaiguo/npc/lingxuzi",}),
"阿依娜": ({"a yina","/d/qujing/jisaiguo/npc/ayina",}),
"萨米儿大叔": ({"uncle samui","/d/qujing/jisaiguo/npc/samui",}),
"小和尚": ({"heshang","/d/qujing/jisaiguo/npc/shaodi",}),
"大和尚": ({"heshang","/d/qujing/jisaiguo/npc/heshang",}),
"老和尚": ({"heshang","/d/qujing/jisaiguo/npc/oldmonk",}),
"书生": ({"shu sheng","/d/qujing/jisaiguo/npc/shusheng",}),
"樵夫": ({"qiao fu","/d/qujing/jisaiguo/npc/qiaofu",}),
"刘老板": ({"liu laoban","/d/qujing/jisaiguo/npc/laoban",}),
"小贩": ({"xiao fan","/d/qujing/jisaiguo/npc/xiaofan",}),
"苦宿禅师": ({"kusu chanshi","/d/qujing/jisaiguo/npc/kusu",}),
"伙计": ({"huoji","/d/qujing/jisaiguo/npc/huoji",}),
//qujing/kusong:
"苍狼怪": ({"yao guai","/d/qujing/kusong/npc/yao1",}),
"兔头怪": ({"yao guai","/d/qujing/kusong/npc/yao2",}),
"山妖": ({"shan yao","/d/qujing/kusong/npc/shanyao",}),
"掀烘兴": ({"xianhong xing","/d/qujing/kusong/npc/xian",}),
"红孩儿": ({"honghai er","/d/qujing/kusong/npc/honghaier",}),
"快如风": ({"kuairu feng","/d/qujing/kusong/npc/kuairufeng",}),
"小妖": ({"xiao yao","/d/qujing/kusong/npc/xiaoyao",}),
"蝙蝠精": ({"bianfu jing","/d/qujing/kusong/npc/bianfu",}),
"蚂蟥怪": ({"mahuang guai","/d/qujing/kusong/npc/mahuang",}),
//qujing/lingshan:
"仙童": ({"xian tong","/d/qujing/lingshan/npc/xiantong",}),
"白雄尊者": ({"baixiong zunzhe","/d/qujing/lingshan/npc/baixiong",}),
"比丘尼": ({"biqiu ni","/d/qujing/lingshan/npc/biqiu",}),
"迦叶尊者": ({"jiaye zunzhe","/d/qujing/lingshan/npc/jiaye",}),
"阿傩尊者": ({"anuo zunzhe","/d/qujing/lingshan/npc/anuo",}),
"阿罗": ({"a luo","/d/qujing/lingshan/npc/monk",}),
"金顶大仙": ({"jinding daxian","/d/qujing/lingshan/npc/jinding",}),
"优婆塞": ({"youpo sai","/d/qujing/lingshan/npc/youpo",}),
"菩萨": ({"pu sa","/d/qujing/lingshan/npc/pusa",}),
"接引佛祖": ({"jieyin fuzu","/d/qujing/lingshan/npc/jieyin",}),
"孔雀大明王": ({"kongque mingwang","/d/xueshan/npc/kongque",}),
"金刚": ({"jin gang","/d/qujing/lingshan/npc/jingang",}),
"如来佛": ({"rulai fo","/d/qujing/lingshan/npc/rulai",}),
"农妇": ({"nong fu","/d/qujing/lingshan/npc/people",}),
"燃灯古佛": ({"randeng gufo","/d/qujing/lingshan/npc/randeng",}),
//qujing/nuerguo:
"中年妇女": ({"woman","/d/qujing/nuerguo/npc/woman1",}),
"老妇人": ({"old woman","/d/qujing/nuerguo/npc/woman2",}),
"老婆婆": ({"old woman","/d/qujing/nuerguo/npc/oldwoman",}),
"道士": ({"daoshi","/d/qujing/nuerguo/npc/daoshi",}),
"宫女": ({"girl","/d/qujing/nuerguo/npc/girl",}),
"梅鸳鸯": ({"mei yuanyan","/d/qujing/nuerguo/npc/lady",}),
"小公主": ({"xiliang princess","/d/qujing/nuerguo/npc/princess",}),
"牛二先生": ({"niuer","/d/qujing/nuerguo/npc/niuer",}),
//qujing/pansi:
"金莲": ({"jin lian","/d/qujing/pansi/npc/girl6",}),
"绛裙": ({"jiang qun","/d/qujing/pansi/npc/girl7",}),
"小童": ({"xiao tong","/d/qujing/pansi/npc/xiaotong",}),
"道士": ({"dao shi","/d/qujing/pansi/npc/xie3",}),
"道士": ({"dao shi","/d/qujing/pansi/npc/xie4",}),
"道士": ({"dao shi","/d/qujing/pansi/npc/xie1",}),
"道士": ({"dao shi","/d/qujing/pansi/npc/xie2",}),
"钗头": ({"chai tou","/d/qujing/pansi/npc/girl5",}),
"檀口": ({"tan kou","/d/qujing/pansi/npc/girl4",}),
"玉香": ({"yu xiang","/d/qujing/pansi/npc/girl1",}),
"道士": ({"dao shi","/d/qujing/pansi/npc/dao",}),
"断肠妇人": ({"duanchang furen","/d/qujing/pansi/npc/woman",}),
"花语": ({"hua yu","/d/qujing/pansi/npc/girl2",}),
"柳眉": ({"liu mei","/d/qujing/pansi/npc/girl3",}),
"水蛭精": ({"shuizhi jing","/d/qujing/pansi/npc/shuizhi",}),
"卢": ({"lu","/d/qujing/pansi/npc/son3",}),
"班": ({"ban","/d/qujing/pansi/npc/son4",}),
"蜢": ({"meng","/d/qujing/pansi/npc/son5",}),
"蜡": ({"la","/d/qujing/pansi/npc/son6",}),
"蜜": ({"mi","/d/qujing/pansi/npc/son1",}),
"蜻": ({"qing","/d/qujing/pansi/npc/son7",}),
"蚂": ({"ma","/d/qujing/pansi/npc/son2",}),
//qujing/pingding:
"小妖": ({"xiao yao","/d/qujing/pingding/npc/yao2",}),
"狐阿七大王": ({"huaqi dawang","/d/qujing/pingding/npc/huaqi",}),
"老奶奶": ({"lao nainai","/d/qujing/pingding/npc/laonai",}),
"小妖": ({"xiao yao","/d/qujing/pingding/npc/yao1",}),
"金角大王": ({"jinjiao dawang","/d/qujing/pingding/npc/jinjiao",}),
"精细鬼": ({"jingxi gui","/d/qujing/pingding/npc/gui",}),
"伶俐虫": ({"lingli chong","/d/qujing/pingding/npc/chong",}),
"倚海龙": ({"yihai long","/d/qujing/pingding/npc/long",}),
"银角大王": ({"yinjiao dawang","/d/qujing/pingding/npc/yinjiao",}),
//qujing/qilin:
"羊头怪": ({"yao guai","/d/qujing/qilin/npc/nanyao",}),
"金圣宫": ({"jinsheng gong","/d/qujing/qilin/npc/queen",}),
//qujing/qinfa:
"钱寡妇": ({"qian guafu","/d/qujing/qinfa/npc/qian",}),
"郑寡妇": ({"zheng guafu","/d/qujing/qinfa/npc/zheng",}),
"王小二": ({"wang xiaoer","/d/qujing/qinfa/npc/xiaoer",}),
"宫妃": ({"gong fei","/d/qujing/qinfa/npc/girl",}),
"孙小二": ({"sun xiaoer","/d/qujing/qinfa/npc/sun",}),
"军士": ({"jun shi","/d/qujing/qinfa/npc/junshi",}),
"陈小二": ({"chen xiaoer","/d/qujing/qinfa/npc/chen",}),
"国王": ({"guo wang","/d/qujing/qinfa/npc/king",}),
"周小二": ({"zhou xiaoer","/d/qujing/qinfa/npc/zhou",}),
"太监": ({"tai jian","/d/qujing/qinfa/npc/taijian",}),
"艺人": ({"yi ren","/d/qujing/qinfa/npc/people",}),
"赵寡妇": ({"zhao guafu","/d/qujing/qinfa/npc/guafu",}),
"王后": ({"wang hou","/d/qujing/qinfa/npc/queen",}),
"李寡妇": ({"li guafu","/d/qujing/qinfa/npc/li",}),
//qujing/qinglong:
"辟尘大王": ({"pichen dawang","/d/qujing/qinglong/npc/pi3",}),
"辟暑大王": ({"pishu dawang","/d/qujing/qinglong/npc/pi2",}),
"辟寒大王": ({"pihan dawang","/d/qujing/qinglong/npc/pi1",}),
"野牛精": ({"yao jing","/d/qujing/qinglong/npc/yao",}),
"守门牛精": ({"shoumen niujing","/d/qujing/qinglong/npc/xiniu",}),
"牛角大王": ({"niujiao dawang","/d/qujing/qinglong/npc/niujiao",}),
//qujing/shuangcha:
"刘母": ({"liu mama","/d/qujing/shuangcha/npc/liumm",}),
"家佣": ({"jia yong","/d/qujing/shuangcha/npc/yongren",}),
"刘伯钦": ({"liu boqin","/d/qujing/shuangcha/npc/taibao",}),
//qujing/tianzhu:
"史老板": ({"shi laoban","/d/qujing/tianzhu/npc/shi",}),
"太监": ({"tai jian","/d/qujing/tianzhu/npc/taijian",}),
"宫女": ({"gong nu","/d/qujing/tianzhu/npc/girl",}),
"侯郎中": ({"hou langzhong","/d/qujing/tianzhu/npc/hou",}),
"宫兵": ({"gong bing","/d/qujing/tianzhu/npc/bing",}),
"季梅儿": ({"ji meier","/d/qujing/tianzhu/npc/ji",}),
"福嫂": ({"fu sao","/d/qujing/tianzhu/npc/fu",}),
"皇宫伺卫": ({"si wei","/d/qujing/tianzhu/npc/siwei",}),
"修禅僧人": ({"he shang","/d/qujing/tianzhu/npc/monk",}),
"学童": ({"xue tong","/d/qujing/tianzhu/npc/kid",}),
"元先生": ({"yuan xiansheng","/d/qujing/tianzhu/npc/yuan",}),
"魏大嫂": ({"wei dasao","/d/qujing/tianzhu/npc/wei",}),
"吴老板": ({"wu laoban","/d/qujing/tianzhu/npc/wu",}),
"道士": ({"dao shi","/d/qujing/tianzhu/npc/people",}),
"乔老板": ({"qiao laoban","/d/qujing/tianzhu/npc/qiao",}),
"司徒晋宝": ({"situ jinbao","/d/qujing/tianzhu/npc/situ",}),
"舒老板": ({"shu laoban","/d/qujing/tianzhu/npc/shu",}),
"甜妞": ({"tian niu","/d/qujing/tianzhu/npc/tian",}),
"马老板": ({"ma laoban","/d/qujing/tianzhu/npc/ma",}),
"辛儿娘": ({"xiner niang","/d/qujing/tianzhu/npc/xin",}),
"黄汤": ({"huang tang","/d/qujing/tianzhu/npc/huang",}),
"国王": ({"guo wang","/d/qujing/tianzhu/npc/king",}),
"军机大臣": ({"jun ji","/d/qujing/tianzhu/npc/junji",}),
"黛姐": ({"dai jie","/d/qujing/tianzhu/npc/dai",}),
"公主": ({"gong zhu","/d/qujing/tianzhu/npc/fakegirl",}),
"张妈": ({"zhang ma","/d/qujing/tianzhu/npc/zhang",}),
"方丈": ({"fang zhang","/d/qujing/tianzhu/npc/fang",}),
"乐老板": ({"le laoban","/d/qujing/tianzhu/npc/le",}),
"陶娘子": ({"tao niangzi","/d/qujing/tianzhu/npc/tao",}),
"公主": ({"gong zhu","/d/qujing/tianzhu/npc/realgirl",}),
"郭三娘": ({"guo sanniang","/d/qujing/tianzhu/npc/guo",}),
//qujing/tongtian:
"陈四爷": ({"chen","/d/qujing/tongtian/npc/people",}),
"小童": ({"kid","/d/qujing/tongtian/npc/kid",}),
"陈三鲜": ({"chen sanxian","/d/qujing/tongtian/npc/vendor",}),
//qujing/village:
"真真": ({"zhen zhen","/d/qujing/village/npc/girl2",}),
"爱爱": ({"ai ai","/d/qujing/village/npc/girl3",}),
"素素": ({"su su","/d/qujing/village/npc/girl1",}),
"妇人": ({"woman","/d/qujing/village/npc/oldwoman",}),
//qujing/wudidong:
"老张": ({"lao zhang","/d/qujing/wudidong/npc/oldzhang",}),
"女孩": ({"girl","/d/qujing/wudidong/npc/girl",}),
"男孩": ({"boy","/d/qujing/wudidong/npc/boy",}),
"张及第": ({"xiucai","/d/qujing/wudidong/npc/xiucai",}),
"碧鼠精": ({"bi shu","/d/qujing/wudidong/npc/bishu",}),
"张铁臂": ({"blacksmith","/d/qujing/wudidong/npc/smith",}),
"张小二": ({"waiter","/d/qujing/wudidong/npc/waiter",}),
"野狗": ({"dog","/d/qujing/wudidong/npc/dog",}),
"小娃娃": ({"kid","/d/qujing/wudidong/npc/kid",}),
"鼹鼠精": ({"yan shu","/d/qujing/wudidong/npc/yanshu",}),
"狱守": ({"ward","/d/qujing/wudidong/npc/ward",}),
"田鼠精": ({"tian shu","/d/qujing/wudidong/npc/tianshu",}),
"张弟宝": ({"zhang dibao","/d/qujing/wudidong/npc/dibao",}),
//qujing/wuji:
"胖和尚": ({"he shang","/d/qujing/wuji/npc/monk1",}),
"护宫卫士": ({"wei shi","/d/qujing/wuji/npc/weishi",}),
"守寺僧": ({"shousi seng","/d/qujing/wuji/npc/monk2",}),
"山姬": ({"shan ji","/d/qujing/wuji/npc/shanji",}),
"太监": ({"tai jian","/d/qujing/wuji/npc/taijian",}),
"臣子": ({"chen zi","/d/qujing/wuji/npc/chen",}),
"国王": ({"guo wang","/d/qujing/wuji/npc/kingfake",}),
"小贩": ({"xiao fan","/d/qujing/wuji/npc/people",}),
"店小二": ({"xiao er","/d/qujing/wuji/npc/xiaoer",}),
"王后": ({"wang hou","/d/qujing/wuji/npc/queen",}),
"宫妃": ({"gong fei","/d/qujing/wuji/npc/girl",}),
"伺卫官": ({"siwei guan","/d/qujing/wuji/npc/siwei",}),
"太子": ({"tai zi","/d/qujing/wuji/npc/prince",}),
"叶大嫂": ({"ye dasao","/d/qujing/wuji/npc/vender",}),
//qujing/wuzhuang:
"曹国舅": ({"cao guojiu","/d/qujing/wuzhuang/npc/caoguojiu",}),
"清风": ({"qing feng","/d/qujing/wuzhuang/npc/qingfeng",}),
"韩湘子": ({"han xiangzi","/d/qujing/wuzhuang/npc/hanxiangzi",}),
"蓝采和": ({"lan caihe","/d/qujing/wuzhuang/npc/lancaihe",}),
"何仙姑": ({"he xiangu","/d/qujing/wuzhuang/npc/hexiangu",}),
"农家女": ({"girl","/d/qujing/wuzhuang/npc/girl",}),
"汉钟离": ({"han zhongli","/d/qujing/wuzhuang/npc/hanzhongli",}),
"铁拐李": ({"tieguai li","/d/qujing/wuzhuang/npc/tieguaili",}),
"明月": ({"ming yue","/d/qujing/wuzhuang/npc/mingyue",}),
"镇元大仙": ({"zhenyuan daxian","/d/qujing/wuzhuang/npc/zhenyuan",}),
//qujing/xiaoxitian:
"小童": ({"xiao tong","/d/qujing/xiaoxitian/npc/tong",}),
"小童": ({"xiao tong","/d/qujing/xiaoxitian/npc/xiaotong",}),
"黄眉老佛": ({"huangmei laofo","/d/qujing/xiaoxitian/npc/huangmei",}),
//qujing/yinwu:
"妖王": ({"yao wang","/d/qujing/yinwu/npc/yaowang",}),
"小妖": ({"xiao yao","/d/qujing/yinwu/npc/xiaoyao",}),
"老妇": ({"lao fu","/d/qujing/yinwu/npc/laofu",}),
"山妖": ({"shan yao","/d/qujing/yinwu/npc/shanyao",}),
"樵子": ({"qiao zi","/d/qujing/yinwu/npc/qiaozi",}),
"妖精": ({"yao jing","/d/qujing/yinwu/npc/yaojing",}),
//qujing/yuhua:
"殿官": ({"dian guan","/d/qujing/yuhua/npc/dianguan",}),
"老王爷": ({"lao wangye","/d/qujing/yuhua/npc/prince",}),
"市民": ({"shi min","/d/qujing/yuhua/npc/people",}),
"小王子": ({"xiao wangzi","/d/qujing/yuhua/npc/prince3",}),
"铁匠": ({"tie jiang","/d/qujing/yuhua/npc/tiejiang",}),
"差官": ({"chai guan","/d/qujing/yuhua/npc/chaiguan",}),
"士兵": ({"shi bing","/d/qujing/yuhua/npc/bing",}),
"酒保": ({"jiu bao","/d/qujing/yuhua/npc/jiubao",}),
"歌女": ({"ge nu","/d/qujing/yuhua/npc/genu",}),
"二王子": ({"er wangzi","/d/qujing/yuhua/npc/prince2",}),
"大王子": ({"da wangzi","/d/qujing/yuhua/npc/prince1",}),
//qujing/yunzhan:
"翠兰": ({"cui lan","/d/qujing/yunzhan/npc/lady",}),
//qujing/zhujie:
"双尾虎": ({"yao guai","/d/qujing/zhujie/npc/yao",}),
"青毛狮": ({"qingmao shi","/d/sea/npc/beast/beast5",}),
"九头狮": ({"jiutou shi","/d/qujing/zhujie/npc/shi",}),
//qujing/zhuzi:
"僧侣": ({"seng lu","/d/qujing/zhuzi/npc/people",}),
"校尉": ({"xiao wei","/d/qujing/zhuzi/npc/xiaowei",}),
"太监": ({"tai jian","/d/qujing/zhuzi/npc/taijian",}),
"宫妃": ({"gong fei","/d/qujing/zhuzi/npc/girl",}),
"瘦店娘": ({"shou dianniang","/d/qujing/zhuzi/npc/shou",}),
"胖店主": ({"pang dianzhu","/d/qujing/zhuzi/npc/pang",}),
"鹤发老童": ({"hefa laotong","/d/qujing/zhuzi/npc/laotong",}),
"国王": ({"guo wang","/d/qujing/zhuzi/npc/king",}),
"米老板": ({"mi laoban","/d/qujing/zhuzi/npc/mi",}),
"柳光头": ({"liu guangtou","/d/qujing/zhuzi/npc/liuguang",}),
"醉方休": ({"zui fangxiu","/d/qujing/zhuzi/npc/zui",}),
"万口福": ({"wan koufu","/d/qujing/zhuzi/npc/wan",}),
"茶花娘子": ({"chahua niangzi","/d/qujing/zhuzi/npc/cha",}),
]);

mapping Items = ([
	"项链" : ({ ({"xiang lian","neck",}),"串","一串明光闪闪的项链。\n",}),
	"戒指" : ({ ({"jie zhi","ring",}),"枚","一枚贵气逼人的戒指。\n",}),
	"密信" : ({ ({"mi xin","xin","letter",}),"封","一封火漆封口的信。\n",}),
	"寿元丹" : ({ ({"shou yuan dan","dan yao",}), "粒","一粒终南山炼制的丹药，吃了能让人增加寿元。\n",}),
	"布料" : ({ ({"bu liao","bu",}),"匹","一匹产自岭南的粗布料。\n",}),
	"丝绸" : ({ ({"si chou","chou",}),"匹","一匹产自江南的丝绸。\n",}),
]);

string query_place(string dir0)
{
	string filename="/adm/daemons/find.map";
   	string buf, *buf1;
   	string dir, name,tmp,temp;
   	int size,n,i,m;
	buf=read_file(filename);
   	if(!buf) return "不知啥地方";
	buf1=explode(buf,"\n");
   	size=sizeof(buf1);
   	if(!size) return "不知啥地方";
	reset_eval_cost();   	
	for(i=0;i<size;i++) 
	{
    	if(sscanf(buf1[i],"%s %s",dir,name)==2) 
    	{
    		if( dir==dir0 )
    		{
       			name=replace_string(name," ","");
				n = strlen(name);
				if( n>2 )
				{
					m = random(n/2)*2;
					tmp = sprintf("%s",name[m..m+1]);
					name = replace_string(name,tmp,"□");
				}
				temp = name;
				temp = replace_string(temp,"□","");
				while(strlen(temp)>3)
				{
					n = strlen(temp);
					if( n<2 )
						break;
					m = random(n/2)*2;
					temp = sprintf("%s",temp[m..m+1]);
				}
				if( strlen(temp)>1 )
					name = replace_string(name,temp,"□");
       			return name;
       		}
		}
	}
	return "不知啥地方";	
}
