#include <ansi.h>
#define Max_count 10
#define MAXDELAY   80

mapping color_code=([
    "zhu bajie": HIR"红"NOR,
    "chen guangrui": HIG"绿"NOR,
    "hu jingde": HIY"黄"NOR,
    "xiang gong": HIB"蓝"NOR,
    "xiang po": HIM"粉"NOR,
    "yin wenjiao": HIC"青"NOR,
//	"yu lan":HIR"红"NOR,
//	"cui lan":HIM"粉"NOR,
//	"xiang lan":HIB"蓝"NOR,
	"xiang lan":HIW"白"NOR,
]);

string my_color=WHT"灰"NOR;

string *npc_file = ({
"/d/baihuagu/npc/ningmou",
"/d/baihuagu/npc/moon",
"/d/jz/npc/people",
"/d/changan/npc/jingwei",
"/d/changan/npc/fisher",
"/d/changan/npc/qiaofu",
"/d/city/npc/leigong",
"/d/wiz/flower/npc/flowerseller",
"/d/sea/npc/long7",
"/d/city/npc/bing",
"/d/city/npc/wujiang",
"/d/changan/npc/huang",
"/d/changan/officer",
"/d/xueshan/npc/shenying-shizhe",
"/d/sea/npc/long1",
"/d/changan/npc/tiesp",
"/d/changan/npc/lusheng",
"/d/city/npc/tiesuanpan",
"/d/city/npc/zhaodaoluan",
"/d/city/npc/zhudachang",
"/d/city/npc/thief",
"/d/city/npc/liumang",
"/d/city/npc/xiaoxiao",
"/d/city/npc/bookseller",
"/d/city/npc/xiushi",
"/d/city/npc/yuanshouchen",
"/d/qujing/wuzhuang/npc/zhangguolao",
"/d/city/npc/libai",
"/d/city/npc/keeper",
"/d/city/npc/gongsun",
"/d/city/npc/pig_counter",
"/d/city/npc/teawaiter",
"/d/city/npc/suanxiucai",
"/d/city/npc/pablo",
"/d/city/npc/qianke",
"/d/city/npc/zhuangd",
"/d/city/npc/jixian",
"/d/city/npc/guitong",
"/d/city/npc/xiaoyi",
"/d/city/npc/age",
"/d/city/npc/faming",
"/d/city/npc/huangfeihong",
"/d/city/npc/xiucai4",
"/d/city/npc/wuji",
"/d/city/npc/xiucai1",
"/d/city/npc/xiucai2",
"/d/city/npc/sengren",
"/d/city/npc/sengren1",
"/d/city/npc/xiaoer",
"/d/ourhome/npc/bigeye",
"/d/wiz/npc/liwu",
"/d/city/npc/family",
"/d/city/npc/liwu",
"/d/city/npc/laosun",
"/d/eastway/npc/man",
"/d/city/npc/liyu",
"/d/city/npc/girl",
"/d/city/npc/xiaopizi",
"/d/qujing/wudidong/npc/bianfu",
"/d/city/npc/boy",
"/d/city/npc/woman",
"/d/wiz/npc/paimaishi",
"/d/city/npc/youxia",
"/d/city/npc/daozhang",
"/d/lingtai/npc/xiao",
"/d/city/npc/fei1",
"/d/city/npc/tangzhu1",
"/d/city/npc/fei2",
"/d/wiz/npc/spirit",
"/d/city/npc/yuantiangang",
"/d/city/npc/jiaotou",
"/d/city/npc/dizi",
"/d/city/npc/fan",
"/quest/biao/npc",
"/d/city/npc/xiaoliu",
"/d/city/npc/eryi",
"/d/city/npc/boss",
"/d/city/npc/heshang",
"/d/city/npc/yang",
"/d/city/npc/laotou",
"/d/xueshan/npc/xunshi-out",
"/d/city/npc/laowei",
"/d/city/npc/vikee",
"/d/city/npc/jieding",
"/d/nanhai/npc/bonze",
"/d/penglai/npc/laitou",
"/d/death/npc/duanzhu",
"/d/death/npc/dizhang",
"/d/death/npc/pang",
"/d/death/npc/bgargoyle",
"/d/death/npc/niutou",
"/d/death/npc/mamian",
"/d/death/npc/shizhe",
"/d/death/npc/yinchangsheng",
"/d/death/npc/wangfangping",
"/d/death/npc/mingwang",
"/d/death/npc/genggui",
"/d/death/npc/shentu",
"/d/death/npc/yulei",
"/d/death/npc/heiwuchang",
"/d/death/npc/baiwuchang",
"/d/death/npc/lunzhuanwang",
"/d/death/npc/tong",
"/d/death/npc/bianchengwang",
"/d/death/npc/dushiwang",
"/d/death/npc/taishanwang",
"/d/death/npc/pingdengwang",
"/d/death/npc/chuguanwang",
"/d/death/npc/songdiwang",
"/d/death/npc/chujiangwang",
"/d/death/npc/qinguangwang",
"/d/shendian/babu/yecha",
"/d/death/npc/gousiren",
"/d/death/npc/tong1",
"/d/death/npc/tong2",
"/d/death/npc/yanluowang",
"/d/eastway/npc/sengren",
"/d/eastway/npc/luren",
"/d/eastway/npc/dai",
"/d/eastway/npc/xiucai",
"/d/eastway/npc/petboss",
"/d/eastway/npc/bosswife",
"/d/eastway/npc/bing",
"/d/eastway/npc/wujiang",
"/d/eastway/npc/furen",
"/d/eastway/npc/youke",
"/d/eastway/npc/girl",
"/d/gao/npc/pangsao",
"/d/gao/npc/cunzhang",
"/d/gao/npc/farmer",
"/d/gao/npc/yahuan",
"/d/gao/npc/laoyu",
"/d/gao/npc/wang",
"/d/gao/npc/jiuke",
"/d/gao/npc/jiading",
"/d/gao/npc/gaopo",
"/d/gao/npc/yahuan1",
"/d/gao/npc/xiaofan",
"/d/gao/npc/zhu",
"/d/gao/npc/laoli",
"/d/gao/npc/xuetu",
"/d/gao/npc/washer",
"/d/gao/npc/kid",
"/d/gao/npc/teacher",
"/d/gao/npc/gaoxiaojie",
"/d/gao/npc/huoji",
"/d/gao/npc/guanjia",
"/d/gao/npc/gao",
"/d/gao/npc/yahuan2",
"/d/jjf/npc/qinfu",
"/d/jjf/npc/xiaotong",
"/d/jjf/npc/guard",
"/d/jjf/npc/qinan",
"/d/jjf/npc/luochun",
"/d/jjf/npc/luocheng",
"/d/jjf/npc/qinping",
"/d/jjf/npc/qinqiong",
"/d/jjf/npc/jiajiang",
"/d/jjf/npc/qinbing",
"/d/jjf/npc/chengyaojin",
"/d/jjf/npc/yuchigong",
"/d/jjf/npc/baifalaoren",
"/d/jjf/npc/pangu",
"/d/jjf/npc/fujiang",
"/d/jjf/npc/qinbing-qi",
"/d/jjf/npc/qinbing-jian",
"/d/jjf/npc/liyuanji",
"/d/jjf/npc/lijiancheng",
"/d/lingtai/npc/yingke",
"/d/lingtai/npc/zhangdaoling",
"/d/lingtai/npc/xiaodao",
"/d/lingtai/npc/yunjing",
"/d/lingtai/npc/wanfeng",
"/d/lingtai/npc/guangyun",
"/d/lingtai/npc/shixong",
"/d/lingtai/npc/yunqing",
"/d/lingtai/npc/huigang",
"/d/lingtai/npc/huiliu",
"/d/lingtai/npc/laodao",
"/d/lingtai/npc/guangxi",
"/d/lingtai/npc/yunyang",
"/d/lingtai/npc/kancai",
"/d/lingtai/npc/swk",
"/d/lingtai/npc/puti",
"/d/lingtai/npc/qiaofu",
"/d/xueshan/npc/qingshi-laomo",
"/d/luoyang/npc/guanjia",
"/d/luoyang/npc/shenxiang",
"/d/luoyang/npc/bing",
"/d/luoyang/npc/wujiang",
"/d/luoyang/npc/bookseller",
"/d/luoyang/npc/xianzhi",
"/d/luoyang/npc/difenghou",
"/d/luoyang/npc/jijian",
"/d/luoyang/npc/gongsun3",
"/d/luoyang/npc/xiaoer",
"/d/luoyang/npc/lai",
"/d/luoyang/npc/fugui",
"/d/luoyang/npc/qingfeng",
"/d/luoyang/npc/xuxingzhi",
"/d/luoyang/npc/xuziling",
"/d/luoyang/npc/shuiwuhan",
"/d/luoyang/npc/jiaotou",
"/d/luoyang/npc/dizi",
"/d/luoyang/npc/guan",
"/d/luoyang/npc/teawater",
"/d/meishan/npc/fisher",
"/d/meishan/npc/fefisher",
"/d/meishan/npc/miaozhu",
"/d/meishan/npc/laotai",
"/d/meishan/npc/erlang",
"/d/meishan/npc/cao",
"/d/meishan/npc/luke",
"/d/meishan/npc/guo",
"/d/meishan/npc/zhi",
"/d/meishan/npc/kang",
"/d/meishan/npc/zhangsun",
"/d/meishan/npc/zhang",
"/d/meishan/npc/girl",
"/d/meishan/npc/li",
"/d/meishan/npc/yao",
"/d/moon/npc/change",
"/d/moon/npc/fairy5",
"/d/moon/npc/nuwa",
"/d/moon/npc/fairy3",
"/d/moon/npc/fairy2",
"/d/moon/npc/fairy4",
"/d/moon/npc/chimeng",
"/d/moon/npc/magu",
"/d/moon/npc/girl",
"/d/moon/npc/yutu",
"/d/moon/npc/wugang",
"/d/moon/npc/guishu",
"/d/moon/npc/xiwangmu1",
"/d/moon/npc/fairy1",
"/d/moon/npc/fairy",
"/d/xueshan/npc/xiaozuanfeng",
"/d/moon/npc/yuenu",
"/d/moon/npc/yuelao",
"/d/moon/npc/snshou",
"/d/moon/npc/jiaofu",
"/d/moon/npc/jftou",
"/d/moon/npc/lgshou",
"/d/nanhai/npc/zhangchan",
"/d/nanhai/npc/shancai",
"/d/nanhai/npc/shizhe",
"/d/nanhai/npc/guanyin",
"/d/nanhai/npc/zhike",
"/d/nanhai/npc/huian",
"/d/qujing/wuzhuang/npc/ludongbin",
"/d/nanhai/npc/xingzhe",
"/d/nanhai/npc/shami",
"/d/nanhai/npc/tidu",
"/d/nanhai/npc/bear-monster",
"/d/nanhai/npc/zhangchu",
"/d/pansi/npc/niang",
"/d/pansi/npc/bai",
"/d/pansi/npc/shengmu",
"/d/pansi/npc/jikao",
"/d/pansi/npc/xiang",
"/d/penglai/npc/baihua-xianzi",
"/d/baihuagu/npc/xiaotong",
"/d/penglai/npc/shouxing",
"/d/penglai/npc/fuxing",
"/d/penglai/npc/luxing",
"/d/sea/npc/gongnu",
"/d/sea/npc/longshao",
"/d/sea/npc/long2",
"/d/sea/npc/biaodi",
"/d/sea/npc/long3",
"/d/sea/npc/long6",
"/d/sea/npc/soldier2",
"/d/sea/npc/soldier1",
"/d/sea/npc/qiupo",
"/d/sea/npc/long5",
"/d/sea/npc/longnu",
"/d/sea/npc/beisao",
"/d/sea/npc/beinu",
"/d/shendian/babu/longshen",
"/d/sea/npc/gonge",
"/d/sea/npc/longwang",
"/d/sea/npc/longpo",
"/d/sea/npc/long9",
"/d/sea/npc/gui",
"/d/sea/npc/jing",
"/d/sea/npc/biantidu",
"/d/sea/npc/lizongbing",
"/d/sea/npc/qingdusi",
"/d/sea/npc/zitaiwei",
"/d/sea/npc/yecha",
"/d/sea/npc/kid1",
"/d/sea/npc/kid2",
"/d/sea/npc/kid3",
"/d/sea/npc/long4",
"/d/sea/npc/lishi",
"/d/shushan/npc/jiansheng",
"/d/shushan/npc/jian",
"/d/shushan/npc/qingfeng",
"/d/shushan/npc/zuidao",
"/d/shushan/npc/guard",
"/d/shushan/npc/jiantong",
"/d/shushan/npc/laodao",
"/d/shushan/npc/zhike",
"/d/shushan/npc/fool",
"/d/shushan/npc/lxy",
"/d/shushan/npc/linyueru",
"/d/shendian/babu/axiuluo",
"/d/westway/npc/wujiang",
"/d/qujing/kusong/npc/jiruhuo",
"/d/westway/npc/tanfan",
"/d/westway/npc/xiong",
"/d/westway/npc/yin",
"/d/westway/npc/niu",
"/d/westway/npc/laoren",
"/d/westway/npc/madao",
"/d/xueshan/npc/dapeng",
"/d/xueshan/npc/shier",
"/d/xueshan/npc/huanhua",
"/d/xueshan/npc/xiezi",
"/d/xueshan/npc/xunshi",
"/d/xueshan/npc/yingwu-guai",
"/d/xueshan/npc/baixiang-zunzhe",
"/d/xueshan/npc/tuying-zunzhe",
"/d/xueshan/npc/huangque-shier",
"/d/xueshan/npc/kongque-gongzhu",
"/d/shendian/babu/jialouluo",
"/d/xueshan/npc/wuya-guai",
"/d/ourhome/honglou/npc/fairygirl",
"/d/ourhome/honglou/npc/leng",
"/d/ourhome/honglou/npc/poemgirl",
"/d/qujing/wuzhuang/npc/zhenyuan",
"/d/qujing/wuzhuang/npc/mingyue",
"/d/qujing/wuzhuang/npc/tieguaili",
"/d/qujing/wuzhuang/npc/hanzhongli",
"/d/qujing/wuzhuang/npc/girl",
"/d/qujing/wuzhuang/npc/hexiangu",
"/d/qujing/wuzhuang/npc/lancaihe",
"/d/qujing/wuzhuang/npc/hanxiangzi",
"/d/qujing/wuzhuang/npc/qingfeng",
"/d/qujing/wuzhuang/npc/caoguojiu",
"/d/qujing/baotou/npc/dzgg",
"/d/qujing/baotou/npc/ggdz",
"/d/qujing/baoxiang/npc/shanyao",
"/d/qujing/baoxiang/npc/people",
"/d/qujing/baoxiang/npc/bing",
"/d/qujing/baoxiang/npc/baihua",
"/d/qujing/baoxiang/npc/huangpao",
"/d/qujing/baoxiang/npc/dashi",
"/d/qujing/baoxiang/npc/girl",
"/d/qujing/baoxiang/npc/king",
"/d/qujing/baoxiang/npc/xijiang",
"/d/qujing/baoxiang/npc/laoban",
"/d/qujing/baoxiang/npc/nuzi",
"/d/qujing/baoxiang/npc/fangzhu",
"/d/qujing/bibotan/npc/luniang",
"/d/qujing/bibotan/npc/shanyao",
"/d/qujing/bibotan/npc/fuma",
"/d/qujing/bibotan/npc/gongzhu",
"/d/qujing/bibotan/npc/longwang",
"/d/qujing/bibotan/npc/dadu",
"/d/qujing/bibotan/npc/hunter",
"/d/qujing/bibotan/npc/niqiu",
"/d/qujing/bibotan/npc/qingshan",
"/d/qujing/bibotan/npc/changtui",
"/d/qujing/bibotan/npc/gui",
"/d/qujing/bibotan/npc/bie",
"/d/qujing/biqiu/npc/taijian",
"/d/qujing/biqiu/npc/king",
"/d/qujing/biqiu/npc/guozhang",
"/d/qujing/biqiu/npc/binumuyi",
"/d/qujing/biqiu/npc/wenguan",
"/d/qujing/biqiu/npc/people",
"/d/qujing/biqiu/npc/lasulusi",
"/d/qujing/biqiu/npc/suohana",
"/d/qujing/biqiu/npc/kanduli",
"/d/qujing/biqiu/npc/kusikusi",
"/d/qujing/biqiu/npc/hou",
"/d/qujing/biqiu/npc/girl",
"/d/qujing/chechi/npc/people",
"/d/qujing/chechi/npc/daguan",
"/d/qujing/chechi/npc/heshang",
"/d/qujing/chechi/npc/daozhang",
"/d/qujing/chechi/npc/feng",
"/d/qujing/chechi/npc/taijian",
"/d/city/npc/biaotou",
"/d/qujing/chechi/npc/weishi",
"/d/qujing/chechi/npc/daotong",
"/d/qujing/chechi/npc/girl",
"/d/qujing/chechi/npc/king",
"/d/qujing/chechi/npc/jz1",
"/d/qujing/chechi/npc/jiubao",
"/d/qujing/chechi/npc/long",
"/d/qujing/chechi/npc/langli",
"/d/qujing/chechi/npc/beili",
"/d/qujing/chechi/npc/chaili",
"/d/qujing/chechi/npc/mali",
"/d/qujing/chechi/npc/jz3",
"/d/qujing/chechi/npc/lingbao",
"/d/qujing/chechi/npc/yuanshi",
"/d/qujing/chechi/npc/taishang",
"/d/qujing/chechi/npc/shulao",
"/d/qujing/chechi/npc/jz2",
"/d/qujing/chechi/npc/daoshi",
"/d/qujing/chechi/npc/xiaoguan",
"/d/qujing/chechi/npc/xizi",
"/d/qujing/chechi/npc/jinchai",
"/d/qujing/dudi/npc/yao",
"/d/qujing/dudi/npc/xiezi",
"/d/qujing/fengxian/npc/people2",
"/d/qujing/fengxian/npc/fashi",
"/d/qujing/fengxian/npc/people",
"/d/qujing/fengxian/npc/sg2",
"/d/qujing/fengxian/npc/jiguan",
"/d/qujing/fengxian/npc/sg3",
"/d/qujing/fengxian/npc/sg",
"/d/qujing/fengxian/npc/sg4",
"/d/qujing/fengxian/npc/monk",
"/d/qujing/fengxian/npc/miaozhu",
"/d/qujing/fengxian/npc/sg1",
"/d/qujing/firemount/npc/qiaofu",
"/d/qujing/firemount/npc/xiaoyao",
"/d/qujing/firemount/npc/oldman",
"/d/qujing/firemount/npc/huoyun",
"/d/sea/npc/long8",
"/d/qujing/firemount/npc/bajiaoq",
"/d/qujing/firemount/npc/bajiao",
"/d/qujing/firemount/npc/bajiaob",
"/d/qujing/firemount/npc/vendor",
"/d/qujing/jilei/npc/yao",
"/d/qujing/jilei/npc/niumo",
"/d/qujing/jilei/npc/yumian",
"/d/qujing/jindou/npc/dujiao",
"/d/qujing/jingjiling/npc/bo",
"/d/qujing/jingjiling/npc/hui",
"/d/qujing/jingjiling/npc/guard",
"/d/qujing/jingjiling/npc/song",
"/d/qujing/jingjiling/npc/xing",
"/d/qujing/jingjiling/npc/zhu",
"/d/qujing/jinping/npc/fuling",
"/d/qujing/jinping/npc/guan",
"/d/qujing/jinping/npc/people",
"/d/qujing/jinping/npc/keeper",
"/d/qujing/jinping/npc/dianzhu",
"/d/qujing/jinping/npc/monk",
"/d/qujing/jinping/npc/dengguan",
"/d/qujing/jisaiguo/npc/huoji",
"/d/qujing/jisaiguo/npc/kusu",
"/d/qujing/jisaiguo/npc/xiaofan",
"/d/qujing/jisaiguo/npc/laoban",
"/d/qujing/jisaiguo/npc/qiaofu",
"/d/qujing/jisaiguo/npc/shusheng",
"/d/qujing/jisaiguo/npc/guard",
"/d/qujing/jisaiguo/npc/oldmonk",
"/d/qujing/jisaiguo/npc/heshang",
"/d/qujing/jisaiguo/npc/shaodi",
"/d/qujing/jisaiguo/npc/samui",
"/d/qujing/jisaiguo/npc/ayina",
"/d/qujing/jisaiguo/npc/lingxuzi",
"/d/qujing/jisaiguo/npc/benba",
"/d/qujing/jisaiguo/npc/baben",
"/d/qujing/jisaiguo/npc/king",
"/d/qujing/jisaiguo/npc/doctor",
"/d/qujing/jisaiguo/npc/guan",
"/d/qujing/nuerguo/npc/niuer",
"/d/qujing/nuerguo/npc/princess",
"/d/qujing/nuerguo/npc/girl",
"/d/qujing/nuerguo/npc/lady",
"/d/qujing/nuerguo/npc/daoshi",
"/d/qujing/nuerguo/npc/oldwoman",
"/d/qujing/nuerguo/npc/woman1",
"/d/qujing/nuerguo/npc/woman2",
"/d/qujing/pingding/npc/yinjiao",
"/d/qujing/pingding/npc/long",
"/d/qujing/pingding/npc/hu",
"/d/qujing/pingding/npc/gui",
"/d/qujing/pingding/npc/chong",
"/d/qujing/pingding/npc/jinjiao",
"/d/qujing/pingding/npc/laonai",
"/d/qujing/pingding/npc/huaqi",
"/d/qujing/pansi/npc/xiaotong",
"/d/qujing/pansi/npc/shuizhi",
"/d/qujing/pansi/npc/girl3",
"/d/qujing/pansi/npc/girl2",
"/d/qujing/pansi/npc/woman",
"/d/qujing/pansi/npc/dao",
"/d/qujing/pansi/npc/girl1",
"/d/qujing/pansi/npc/girl5",
"/d/qujing/pansi/npc/girl4",
"/d/qujing/pansi/npc/girl7",
"/d/qujing/pansi/npc/girl6",
"/d/qujing/tongtian/npc/people",
"/d/qujing/tongtian/npc/vendor",
"/d/qujing/tongtian/npc/kid",
"/d/qujing/qilin/npc/nanyao",
"/d/qujing/qilin/npc/yaowang",
"/d/qujing/qilin/npc/queen",
"/d/qujing/qilin/npc/nuyao",
"/d/qujing/qinfa/npc/people",
"/d/qujing/qinfa/npc/li",
"/d/qujing/qinfa/npc/junshi",
"/d/qujing/qinfa/npc/queen",
"/d/qujing/qinfa/npc/guafu",
"/d/qujing/qinfa/npc/taijian",
"/d/qujing/qinfa/npc/zhou",
"/d/qujing/qinfa/npc/king",
"/d/qujing/qinfa/npc/chen",
"/d/qujing/qinfa/npc/sun",
"/d/qujing/qinfa/npc/girl",
"/d/qujing/qinfa/npc/xiaoer",
"/d/qujing/qinfa/npc/zheng",
"/d/qujing/qinfa/npc/qian",
"/d/qujing/qinglong/npc/niujiao",
"/d/qujing/qinglong/npc/xiniu",
"/d/qujing/qinglong/npc/pi1",
"/d/qujing/qinglong/npc/pi2",
"/d/qujing/qinglong/npc/pi3",
"/d/qujing/tianzhu/npc/monk",
"/d/qujing/tianzhu/npc/people",
"/d/qujing/tianzhu/npc/guo",
"/d/qujing/tianzhu/npc/realgirl",
"/d/qujing/tianzhu/npc/tao",
"/d/qujing/tianzhu/npc/le",
"/d/qujing/tianzhu/npc/bing",
"/d/qujing/tianzhu/npc/fang",
"/d/qujing/tianzhu/npc/taijian",
"/d/qujing/tianzhu/npc/zhang",
"/d/qujing/tianzhu/npc/girl",
"/d/qujing/tianzhu/npc/fakegirl",
"/d/qujing/tianzhu/npc/dai",
"/d/qujing/tianzhu/npc/junji",
"/d/qujing/tianzhu/npc/king",
"/d/qujing/tianzhu/npc/huang",
"/d/qujing/tianzhu/npc/xin",
"/d/qujing/tianzhu/npc/ma",
"/d/qujing/tianzhu/npc/tian",
"/d/qujing/tianzhu/npc/shu",
"/d/qujing/tianzhu/npc/situ",
"/d/qujing/tianzhu/npc/qiao",
"/d/qujing/tianzhu/npc/wu",
"/d/qujing/tianzhu/npc/wei",
"/d/qujing/tianzhu/npc/yuan",
"/d/qujing/tianzhu/npc/kid",
"/d/qujing/tianzhu/npc/siwei",
"/d/qujing/tianzhu/npc/fu",
"/d/qujing/tianzhu/npc/ji",
"/d/qujing/tianzhu/npc/hou",
"/d/qujing/tianzhu/npc/shi",
"/d/qujing/wudidong/npc/shumo",
"/d/qujing/wudidong/npc/kanmen",
"/d/qujing/wudidong/npc/dibao",
"/d/qujing/wudidong/npc/dragon",
"/d/qujing/wudidong/npc/tianshu",
"/d/qujing/wudidong/npc/jishu",
"/d/qujing/wudidong/npc/yushu",
"/d/qujing/wudidong/npc/yanshu",
"/d/qujing/wudidong/npc/fangzhang-jail",
"/d/qujing/wudidong/npc/kid",
"/d/qujing/wudidong/npc/waiter",
"/d/qujing/wudidong/npc/smith",
"/d/qujing/wudidong/npc/hudian",
"/d/qujing/wudidong/npc/bishu",
"/d/qujing/wudidong/npc/girl",
"/d/qujing/wudidong/npc/xiucai",
"/d/qujing/wudidong/npc/boy",
"/d/qujing/wudidong/npc/oldzhang",
"/d/qujing/wuji/npc/people",
"/d/qujing/wuji/npc/vender",
"/d/qujing/wuji/npc/prince",
"/d/qujing/wuji/npc/siwei",
"/d/qujing/wuji/npc/girl",
"/d/qujing/wuji/npc/taijian",
"/d/qujing/wuji/npc/queen",
"/d/qujing/wuji/npc/xiaoer",
"/d/qujing/wuji/npc/kingfake",
"/d/qujing/wuji/npc/chen",
"/d/qujing/wuji/npc/shanji",
"/d/qujing/wuji/npc/monk1",
"/d/qujing/wuji/npc/monk2",
"/d/qujing/wuji/npc/weishi",
"/d/qujing/xiaoxitian/npc/tong",
"/d/qujing/xiaoxitian/npc/huangmei",
"/d/qujing/xiaoxitian/npc/xiaotong",
"/d/qujing/yinwu/npc/yaojing",
"/d/qujing/yinwu/npc/qiaozi",
"/d/qujing/yinwu/npc/laofu",
"/d/qujing/yinwu/npc/xiaoyao",
"/d/qujing/yinwu/npc/yaowang",
"/d/qujing/yuhua/npc/chaiguan",
"/d/qujing/yuhua/npc/dianguan",
"/d/qujing/yuhua/npc/prince1",
"/d/qujing/yuhua/npc/prince2",
"/d/qujing/yuhua/npc/bing",
"/d/qujing/yuhua/npc/genu",
"/d/qujing/yuhua/npc/jiubao",
"/d/qujing/yuhua/npc/people",
"/d/qujing/yuhua/npc/tiejiang",
"/d/qujing/yuhua/npc/prince3",
"/d/qujing/yuhua/npc/prince",
"/d/qujing/zhujie/npc/shi",
"/d/qujing/zhuzi/npc/people",
"/d/qujing/zhuzi/npc/xiaowei",
"/d/qujing/zhuzi/npc/cha",
"/d/qujing/zhuzi/npc/wan",
"/d/qujing/zhuzi/npc/taijian",
"/d/qujing/zhuzi/npc/zui",
"/d/qujing/zhuzi/npc/liuguang",
"/d/qujing/zhuzi/npc/mi",
"/d/qujing/zhuzi/npc/king",
"/d/qujing/zhuzi/npc/girl",
"/d/qujing/zhuzi/npc/laotong",
"/d/qujing/zhuzi/npc/shou",
"/d/qujing/zhuzi/npc/pang",
});

string *cloth_file = ({
"/d/obj/book/poem",
"/d/wiz/flower/obj/flower7",
"/d/obj/weapon/archery/mu-arrow",
"/d/obj/weapon/archery/tie-arrow",
"/d/obj/weapon/archery/tie-bow",
"/d/obj/book/chunqiu",
"/d/obj/book/westsword",
"/d/obj/book/basic_blade",
"/d/obj/book/forcebook2",
"/d/obj/book/parrybook2",
"/d/obj/book/quanjing",
"/d/obj/book/balei",
"/d/obj/book/basic_unarmed",
"/d/obj/book/san",
"/d/obj/book/boxing",
"/d/obj/food/huadiao-jiudai",
"/d/obj/food/wuxianghuasheng",
"/d/obj/food/cake",
"/d/moon/obj/jiudai",
"/d/ourhome/obj/huasheng",
"/d/wiz/obj/gift-yaoguai",
"/d/obj/misc/tiaozhanpai",
"/quest/longzhou/duanwu-bag",
"/d/penglai/npc/obj/ditu",
"/d/obj/magic/hmagenta",
"/d/obj/magic/horange",
"/d/obj/magic/hblack",
"/d/obj/magic/hviolet",
"/d/obj/magic/hred",
"/d/obj/magic/hmaroon",
"/d/obj/magic/hpink",
"/d/obj/magic/hamber",
"/d/obj/magic/hindigo",
"/d/obj/magic/hwhite",
"/d/obj/magic/hblue",
"/d/obj/magic/hgreen",
"/d/obj/magic/hbrown",
"/d/obj/magic/hscarlet",
"/d/obj/magic/hyellow",
"/d/maze/beiyin/obj/force",
"/d/city/obj/danping",
"/d/city/obj/yaoping",
"/d/obj/weapon/axe/huafu",
"/d/obj/book/misc",
"/d/ourhome/obj/hdjiudai",
"/d/gao/obj/xiaojie",
"/d/obj/yelian/yunshi",
"/d/obj/book/spearbook",
"/d/obj/book/baguatu",
"/d/obj/weapon/archery/qiankun-bow",
"/d/obj/book/fork_1",
"/d/obj/book/axe_1",
"/d/obj/book/blade_1",
"/d/obj/book/spear_1",
"/d/obj/book/unarmed_1",
"/d/obj/book/mace_1",
"/d/obj/book/whip_1",
"/d/moon/obj/guihuageng",
"/d/obj/flower/juhua",
"/d/obj/flower/rose",
"/d/obj/book/girlbook",
"/d/moon/obj/xuelian",
"/d/obj/flower/yehua",
"/d/obj/flower/guihua",
"/d/xueshan/obj/jiudou",
"/d/moon/obj/jiaozi",
"/d/ourhome/obj/shoes",
"/d/obj/cloth/tianyi",
"/d/pansi/obj/guo",
"/d/pansi/obj/yinsuo",
"/d/penglai/obj/baihuaniang",
"/d/obj/misc/ice",
"/d/obj/weapon/sword/qingfeng",
"/d/xueshan/obj/pingreal",
"/d/obj/misc/seed",
"/d/obj/misc/camera",
"/d/obj/misc/buwawa",
"/d/obj/misc/mallet",
"/d/obj/misc/vase",
"/d/obj/misc/hualan",
"/d/qujing/biqiu/obj/neck",
"/d/obj/yelian/jin",
"/d/qujing/biqiu/obj/elong",
"/d/obj/book/daode",
"/d/qujing/chechi/obj/chantai",
"/d/qujing/chechi/obj/youguo",
"/d/qujing/chechi/obj/guizi",
"/d/qujing/jinping/obj/gang",
"/d/qujing/jisaiguo/obj/silverneck",
"/d/qujing/nuerguo/obj/huasheng",
"/d/qujing/qinfa/obj/chong",
"/d/qujing/qinfa/obj/guo",
"/d/obj/yelian/hantie",
"/d/qujing/tianzhu/obj/huabu",
"/d/qujing/tianzhu/obj/huaqun",
"/d/qujing/tianzhu/obj/huapao",
"/d/qujing/tianzhu/obj/vase",
"/d/qujing/tianzhu/obj/pen",
"/d/obj/food/huasheng",
"/d/qujing/tianzhu/obj/jinjie",
"/d/qujing/tianzhu/obj/baijie",
"/d/obj/yelian/hanyu",
"/d/qujing/tianzhu/obj/zuanjie",
"/d/qujing/tianzhu/obj/huacai",
"/d/qujing/tianzhu/obj/jiansu",
"/d/qujing/tianzhu/obj/zhulan",
"/d/qujing/xiaoxitian/obj/jinnao",
"/d/qujing/yinwu/obj/rou",
"/d/qujing/yuhua/obj/lamb",
"/d/qujing/yuhua/obj/pig",
"/d/obj/weapon/stick/xiangmo",
"/d/qujing/zhuzi/obj/huasheng",
"/d/obj/food/dishes/dish15",
"/d/obj/food/dishes/dish03",
});	

string *kill_file = ({
"/d/city/npc/sengren1",
"/d/city/npc/jiaotou",
"/d/xueshan/npc/xunshi-out",
"/d/nanhai/npc/bonze",
"/d/death/npc/bgargoyle",
"/d/death/npc/yinchangsheng",
"/d/death/npc/wangfangping",
"/d/death/npc/yulei",
"/d/death/npc/shentu",
"/d/death/npc/lunzhuanwang",
"/d/death/npc/chuguanwang",
"/d/death/npc/chujiangwang",
"/d/jjf/npc/hulei",
"/d/sea/npc/beast/beast1",
"/d/lingtai/npc/zhangdaoling",
"/d/lingtai/npc/yunjing",
"/d/lingtai/npc/yunqing",
"/d/lingtai/npc/huiliu",
"/d/lingtai/npc/huigang",
"/d/lingtai/npc/laodao",
"/d/lingtai/npc/kancai",
"/d/lingtai/npc/swk",
"/d/xueshan/npc/qingshi-laomo",
"/d/luoyang/npc/qingfeng",
"/d/luoyang/npc/jiaotou",
"/d/sea/npc/beast/beast6",
"/d/moon/npc/wugang",
"/d/nanhai/npc/shancai",
"/d/nanhai/npc/zhike",
"/d/nanhai/npc/xingzhe",
"/d/nanhai/npc/bear-monster",
"/d/penglai/npc/baiyuan",
"/d/sea/npc/biaodi",
"/d/sea/npc/soldier2",
"/d/sea/npc/qiupo",
"/d/sea/npc/beinu",
"/d/sea/npc/longpo",
"/d/sea/npc/lizongbing",
"/d/sea/npc/biantidu",
"/d/sea/npc/beast1",
"/d/sea/npc/beast3",
"/d/sea/npc/beast2",
"/d/sea/npc/qingdusi",
"/d/sea/npc/zitaiwei",
"/d/sea/npc/yecha",
"/d/sea/npc/beast",
"/d/sea/npc/lishi",
"/d/shushan/npc/dragon1",
"/d/shushan/npc/dragon2",
"/d/shushan/npc/dragon3",
"/d/shushan/npc/dragon4",
"/d/shushan/npc/dragon5",
"/d/shushan/npc/dragon6",
"/d/shushan/npc/dragon7",
"/d/shushan/npc/guard",
"/d/shushan/npc/yao2",
"/d/shushan/npc/yao1",
"/d/shushan/npc/zhike",
"/d/shushan/npc/mingwang",
"/d/shushan/npc/yuanhun",
"/d/shushan/npc/linyueru",
"/d/westway/npc/xiong",
"/d/westway/npc/yin",
"/d/westway/npc/niu",
"/d/xueshan/npc/dapeng",
"/d/xueshan/npc/shier",
"/d/xueshan/npc/huanhua",
"/d/xueshan/npc/xiezi",
"/d/xueshan/npc/xunshi",
"/d/xueshan/npc/xueshanyao",
"/d/xueshan/npc/yingwu-guai",
"/d/xueshan/npc/hama",
"/d/xueshan/npc/zhizhu",
"/d/qujing/wuzhuang/npc/mingyue",
"/d/qujing/wuzhuang/npc/qingfeng",
"/d/qujing/baotou/npc/yaowang",
"/d/qujing/baoxiang/npc/bing",
"/d/qujing/baoxiang/npc/king",
"/d/qujing/baoxiang/npc/nuzi",
"/d/qujing/bibotan/npc/shanyao",
"/d/sea/npc/beast/beast3",
"/d/qujing/bibotan/npc/fuma",
"/d/qujing/bibotan/npc/longwang",
"/d/qujing/bibotan/npc/dadu",
"/d/qujing/bibotan/npc/changtui",
"/d/qujing/bibotan/npc/bie",
"/d/qujing/bibotan/npc/gui",
"/d/qujing/biqiu/npc/king",
"/d/qujing/biqiu/npc/guozhang",
"/d/qujing/biqiu/npc/hou",
"/d/qujing/chechi/npc/king",
"/d/qujing/chechi/npc/beili",
"/d/qujing/chechi/npc/langli",
"/d/qujing/chechi/npc/chaili",
"/d/qujing/chechi/npc/mali",
"/d/qujing/dudi/npc/xiezi",
"/d/qujing/fengxian/npc/monk",
"/d/qujing/firemount/npc/xiaoyao",
"/d/qujing/firemount/npc/huoyun",
"/d/qujing/firemount/npc/bajiaoq",
"/d/sea/npc/beast/beast2",
"/d/qujing/firemount/npc/bajiao",
"/d/qujing/firemount/npc/bajiaob",
"/d/qujing/jilei/npc/jinjing",
"/d/qujing/jilei/npc/yumian",
"/d/qujing/jindou/npc/dujiao",
"/d/qujing/jingjiling/npc/bo",
"/d/qujing/jingjiling/npc/hui",
"/d/qujing/jingjiling/npc/guard",
"/d/qujing/jingjiling/npc/song",
"/d/qujing/jingjiling/npc/zhu",
"/d/qujing/jisaiguo/npc/heshang",
"/d/qujing/jisaiguo/npc/lingxuzi",
"/d/qujing/jisaiguo/npc/benba",
"/d/qujing/jisaiguo/npc/baben",
"/d/qujing/nuerguo/npc/daoshi",
"/d/sea/npc/beast/beast7",
"/d/qujing/pingding/npc/yinjiao",
"/d/qujing/pingding/npc/long",
"/d/qujing/pingding/npc/hu",
"/d/qujing/pingding/npc/gui",
"/d/qujing/pingding/npc/chong",
"/d/qujing/pingding/npc/jinjiao",
"/d/qujing/pingding/npc/yao2",
"/d/qujing/pingding/npc/laonai",
"/d/qujing/pingding/npc/huaqi",
"/d/qujing/pansi/npc/son5",
"/d/qujing/pansi/npc/son7",
"/d/qujing/pansi/npc/son2",
"/d/qujing/pansi/npc/son4",
"/d/qujing/pansi/npc/son6",
"/d/qujing/pansi/npc/son1",
"/d/qujing/pansi/npc/son3",
"/d/qujing/pansi/npc/shuizhi",
"/d/qujing/pansi/npc/girl3",
"/d/qujing/pansi/npc/girl2",
"/d/qujing/pansi/npc/dao",
"/d/qujing/pansi/npc/girl1",
"/d/qujing/pansi/npc/girl5",
"/d/qujing/pansi/npc/girl4",
"/d/qujing/pansi/npc/xie2",
"/d/qujing/pansi/npc/xie1",
"/d/qujing/pansi/npc/xie4",
"/d/qujing/pansi/npc/xie3",
"/d/qujing/pansi/npc/girl7",
"/d/qujing/pansi/npc/girl6",
"/d/qujing/tongtian/npc/jinyu",
"/d/qujing/qilin/npc/yaowang",
"/d/qujing/qilin/npc/queen",
"/d/sea/npc/beast/beast4",
"/d/qujing/qinfa/npc/queen",
"/d/qujing/qinglong/npc/niujiao",
"/d/qujing/qinglong/npc/pi1",
"/d/qujing/qinglong/npc/pi2",
"/d/qujing/qinglong/npc/pi3",
"/d/qujing/tianzhu/npc/bing",
"/d/qujing/tianzhu/npc/fakegirl",
"/d/qujing/wudidong/npc/kanmen",
"/d/qujing/wudidong/npc/shumo",
"/d/qujing/wudidong/npc/dragon",
"/d/qujing/wudidong/npc/ward",
"/d/qujing/wudidong/npc/hudian",
"/d/qujing/wuji/npc/prince",
"/d/qujing/wuji/npc/queen",
"/d/qujing/wuji/npc/kingfake",
"/d/qujing/xiaoxitian/npc/tong",
"/d/qujing/xiaoxitian/npc/huangmei",
"/d/qujing/xiaoxitian/npc/xiaotong",
"/d/qujing/yinwu/npc/shanyao",
"/d/qujing/yinwu/npc/yaowang",
"/d/qujing/yuhua/npc/prince1",
"/d/qujing/yuhua/npc/prince2",
"/d/qujing/yuhua/npc/prince3",
"/d/qujing/yuhua/npc/prince",
"/d/qujing/zhujie/npc/shi",
"/d/sea/npc/beast/beast5",
});	

string *food_file = ({
"/d/obj/food/huadiao-jiudai",
"/d/obj/food/chagan",
"/d/obj/food/wuxianghuasheng",
"/d/obj/food/grape",
"/d/obj/food/pig",
"/d/obj/food/putaogan",
"/d/moon/obj/jiudai",
"/d/ourhome/obj/huasheng",
"/d/ourhome/obj/gourou",
"/d/ourhome/obj/jitui",
"/d/city/obj/haiwan",
"/d/obj/food/cutan",
"/d/ourhome/obj/carrot",
"/d/ourhome/obj/beans",
"/d/ourhome/obj/xbc",
"/d/ourhome/obj/hdjiudai",
"/d/ourhome/obj/hulu",
"/d/lingtai/obj/guo",
"/d/obj/food/chahu",
"/d/moon/obj/xueli",
"/d/moon/obj/snowglass",
"/d/xueshan/obj/jiudou",
"/d/ourhome/obj/dhg",
"/d/ourhome/obj/xqc",
"/d/sea/obj/food",
"/d/obj/food/niupi-jiudai",
"/d/obj/food/egg",
"/d/obj/food/jiunang",
"/d/obj/food/roubing",
"/d/obj/food/zongzi",
"/d/obj/food/xbc",
"/d/obj/food/dhg",
"/d/obj/food/hulu",
"/d/obj/food/carrot",
"/d/obj/food/watermelon",
"/d/qujing/baoxiang/obj/xiwan",
"/d/qujing/baoxiang/obj/xihu",
"/d/qujing/baoxiang/obj/yangtou",
"/d/qujing/baoxiang/obj/zasui",
"/d/qujing/baoxiang/obj/paomo",
"/d/qujing/biqiu/obj/zhengya",
"/d/obj/food/baijiu",
"/d/qujing/biqiu/obj/shaoe",
"/d/qujing/biqiu/obj/tangmian",
"/d/qujing/biqiu/obj/niutang",
"/d/qujing/chechi/obj/roujia",
"/d/qujing/chechi/obj/baiye",
"/d/qujing/chechi/obj/niurou",
"/d/qujing/chechi/obj/jiuhu",
"/d/qujing/chechi/obj/gongguo",
"/d/qujing/chechi/obj/guo",
"/d/qujing/chechi/obj/rice",
"/d/qujing/chechi/obj/kang",
"/d/qujing/dudi/obj/momo",
"/d/qujing/fengxian/obj/tea",
"/d/qujing/fengxian/obj/xifan",
"/d/qujing/fengxian/obj/xiaocai",
"/d/obj/food/kaoji",
"/d/qujing/jilei/obj/rou",
"/d/qujing/jindou/obj/rou",
"/d/qujing/jinping/obj/bing",
"/d/qujing/jinping/obj/gao",
"/d/qujing/jinping/obj/guan",
"/d/qujing/jinping/obj/doufu",
"/d/qujing/jinping/obj/hulu",
"/d/qujing/jinping/obj/mianjin",
"/d/qujing/jinping/obj/ji",
"/d/qujing/jisaiguo/obj/qingzhutong",
"/d/qujing/jisaiguo/obj/yangtui",
"/d/qujing/jisaiguo/obj/xiangsu",
"/d/qujing/jisaiguo/obj/youshi",
"/d/qujing/jisaiguo/obj/tanggao",
"/d/qujing/nuerguo/obj/qiongyao",
"/d/qujing/nuerguo/obj/huasheng",
"/d/qujing/pingding/obj/food",
"/d/qujing/pansi/obj/tea",
"/d/qujing/pansi/obj/mianjin",
"/d/qujing/pansi/obj/doufu",
"/d/qujing/tongtian/obj/zuiluo",
"/d/qujing/tongtian/obj/shaoxia",
"/d/qujing/tongtian/obj/xunyu",
"/d/qujing/tongtian/obj/zhengxie",
"/d/qujing/qilin/obj/rou",
"/d/obj/food/mijiu",
"/d/obj/food/rice",
"/d/obj/food/salt",
"/d/qujing/tianzhu/obj/juzi",
"/d/qujing/tianzhu/obj/bailangua",
"/d/qujing/tianzhu/obj/ganzi",
"/d/qujing/tianzhu/obj/mugua",
"/d/qujing/tianzhu/obj/youzi",
"/d/qujing/tianzhu/obj/fanmugua",
"/d/obj/food/huasheng",
"/d/qujing/tianzhu/obj/jiuzhong",
"/d/qujing/tianzhu/obj/jiuguan",
"/d/qujing/tianzhu/obj/jiuhu",
"/d/qujing/tianzhu/obj/doufugeng",
"/d/qujing/tianzhu/obj/luweigan",
"/d/qujing/tianzhu/obj/hongcha",
"/d/qujing/tianzhu/obj/lucha",
"/d/qujing/tianzhu/obj/youzhagan",
"/d/qujing/tianzhu/obj/chougan",
"/d/qujing/tianzhu/obj/mogu",
"/d/qujing/tianzhu/obj/douya",
"/d/qujing/tianzhu/obj/muer",
"/d/qujing/tianzhu/obj/huacai",
"/d/qujing/tianzhu/obj/shansun",
"/d/qujing/tianzhu/obj/xiancai",
"/d/qujing/tianzhu/obj/chaodou",
"/d/qujing/tianzhu/obj/guazi",
"/d/qujing/tianzhu/obj/jiansu",
"/d/qujing/tianzhu/obj/dangao",
"/d/obj/food/xueli",
"/d/obj/food/apple",
"/d/obj/food/strawberry",
"/d/obj/food/mellon",
"/d/qujing/xiaoxitian/obj/zhaiguo",
"/d/qujing/yinwu/obj/rou",
"/d/qujing/yuhua/obj/lamb",
"/d/qujing/yuhua/obj/pig",
"/d/qujing/zhuzi/obj/guazi",
"/d/qujing/zhuzi/obj/chagan",
"/d/qujing/zhuzi/obj/huasheng",
"/d/obj/food/dishes/dish08",
"/d/obj/food/dishes/dish15",
"/d/obj/food/dishes/dish02",
"/d/obj/food/dishes/dish22",
"/d/obj/food/dishes/dish16",
"/d/obj/food/dishes/dish03",
"/d/obj/food/dishes/dish10",
"/d/obj/food/dishes/dish17",
"/d/obj/food/dishes/dish04",
"/d/obj/food/dishes/dish11",
"/d/obj/food/dishes/dish05",
"/d/obj/food/dishes/dish18",
"/d/obj/food/dishes/dish12",
"/d/obj/food/dishes/dish19",
"/d/obj/food/dishes/dish09",
"/d/obj/food/dishes/dish06",
"/d/obj/food/dishes/dish13",
"/d/obj/food/dishes/dish20",
"/d/obj/food/dishes/dish07",
"/d/obj/food/dishes/dish14",
"/d/obj/food/dishes/dish01",
"/d/obj/food/dishes/dish21",
"/d/qujing/zhuzi/obj/miantiao",
"/d/qujing/zhuzi/obj/jianjiao",
"/d/qujing/zhuzi/obj/miantang",
"/d/qujing/zhuzi/obj/shuijiao",
"/d/qujing/zhuzi/obj/mianpian",
"/d/obj/food/niangao",
"/d/obj/food/youhulu",
"/d/qujing/zhuzi/obj/yao",
});
		
string *armor_file = ({
"/d/moon/obj/luoyi",
"/d/ourhome/obj/linen",
"/d/lingtai/obj/xiangpao",
"/d/obj/cloth/skirt",
"/d/obj/armor/yinjia",
"/d/obj/cloth/bingfu",
"/d/obj/narmor/armor",
"/d/obj/armor/jinjia",
"/d/gao/obj/changpao",
"/d/obj/armor/tenjia",
"/d/obj/cloth/xueshan-pao",
"/d/ourhome/obj/choupao",
"/d/obj/cloth/choupao",
"/d/obj/narmor/cloth",
"/d/obj/cloth/linen",
"/d/obj/cloth/changpao",
"/d/obj/narmor/shoes",
"/obj/cloth",
"/d/obj/cloth/pobuxie",
"/d/obj/cloth/shoes",
"/d/city/obj/jiezhi",
"/d/obj/cloth/magua",
"/d/obj/cloth/monkcloth",
"/d/obj/cloth/sengyi",
"/d/obj/cloth/xianpao",
"/d/obj/cloth/pink_cloth",
"/d/obj/cloth/pobuyi",
"/d/obj/narmor/kui",
"/d/lingtai/obj/cloth",
"/d/obj/cloth/piyi",
"/d/obj/cloth/baguapao",
"/d/obj/cloth/yuanxiang",
"/d/obj/cloth/nichang",
"/d/nanhai/obj/sengpao",
"/d/penglai/npc/obj/sengxie",
"/d/obj/cloth/baipao",
"/d/obj/cloth/hei",
"/d/obj/armor/shoupi",
"/d/obj/cloth/taijicloth",
"/d/obj/armor/gujia",
"/d/obj/cloth/bai",
"/d/obj/cloth/mangpao",
"/d/obj/cloth/ziyi",
"/d/obj/cloth/huangyi",
"/d/obj/armor/tiejia",
"/d/gao/obj/ao",
"/d/gao/obj/pink_cloth",
"/d/obj/armor/tongjia",
"/d/gao/obj/piyi",
"/d/gao/obj/magua",
"/d/qujing/kusong/obj/tongjia",
"/d/qujing/bibotan/obj/zhanpao",
"/d/obj/cloth/zhanpao",
"/d/obj/cloth/jinpao",
"/d/obj/cloth/pinkskirt",
"/d/lingtai/obj/faguan",
"/d/lingtai/obj/heao",
"/d/obj/armor/niupi",
"/d/lingtai/obj/daoguanq",
"/d/lingtai/obj/daoguan",
"/d/lingtai/obj/shoe",
"/d/lingtai/obj/pao",
"/d/obj/cloth/luoyi",
"/d/ourhome/obj/shoes",
"/d/ourhome/obj/pink_cloth",
"/d/ourhome/obj/skirt",
"/d/obj/cloth/xianyi",
"/d/nanhai/obj/jiasha",
"/d/obj/cloth/tianyi",
"/d/npc/obj/pifeng",
"/d/npc/obj/armor",
"/d/obj/flower/rose",
"/d/sea/obj/bei",
"/d/sea/obj/longpao",
"/d/ourhome/obj/ironarmor",
"/d/obj/cloth/daopao",
"/d/qujing/jilei/obj/armor",
"/d/obj/cloth/shoupiqun",
"/d/obj/cloth/jinjinyi",
"/d/westway/obj/pao2",
"/d/westway/obj/pao1",
"/d/westway/obj/pao3",
"/d/xueshan/obj/nihong-yuyi",
"/d/obj/cloth/lancaoxie",
"/d/qujing/baotou/obj/cloth1",
"/d/qujing/baoxiang/obj/spqun",
"/d/qujing/baoxiang/obj/changpao",
"/d/qujing/baoxiang/obj/zhanpao",
"/d/qujing/baoxiang/obj/sppifeng",
"/d/qujing/baoxiang/obj/gongpao",
"/d/qujing/bibotan/obj/clasp",
"/d/qujing/chechi/obj/gongpao",
"/d/obj/cloth/longpao",
"/d/obj/cloth/gongpao",
"/d/qujing/biqiu/obj/armor",
"/d/obj/cloth/p_cloth",
"/d/qujing/biqiu/obj/wrists",
"/d/qujing/biqiu/obj/neck",
"/d/qujing/biqiu/obj/ring",
"/d/qujing/chechi/obj/changpao",
"/d/qujing/chechi/obj/gongqun",
"/d/qujing/dudi/obj/cloth",
"/d/qujing/firemount/obj/skirt",
"/d/qujing/jindou/obj/wrists",
"/d/qujing/jindou/obj/neck",
"/d/qujing/jindou/obj/waist",
"/d/qujing/jindou/obj/head",
"/d/qujing/jindou/obj/hands",
"/d/qujing/jindou/obj/finger",
"/d/qujing/jindou/obj/boots",
"/d/qujing/jingjiling/obj/cloth",
"/d/qujing/jingjiling/obj/armor",
"/d/qujing/jinping/obj/denglong31",
"/d/qujing/jinping/obj/denglong34",
"/d/qujing/jinping/obj/denglong33",
"/d/qujing/jinping/obj/denglong30",
"/d/qujing/jinping/obj/denglong32",
"/d/obj/cloth/hufa-jiasha",
"/d/qujing/jisaiguo/obj/changpao",
"/d/obj/misc/necklace",
"/d/obj/cloth/huazheboots",
"/d/qujing/nuerguo/obj/skirt",
"/d/obj/cloth/shoupipifeng",
"/d/qujing/pingding/obj/armor",
"/d/obj/cloth/shoupi",
"/d/qujing/tongtian/obj/cloth",
"/d/qujing/tongtian/obj/skirt",
"/d/qujing/tongtian/obj/armor",
"/d/qujing/qilin/obj/shield",
"/d/qujing/qinglong/obj/shield",
"/d/qujing/tianzhu/obj/yinjie",
"/d/qujing/tianzhu/obj/huaqun",
"/d/qujing/tianzhu/obj/longguan",
"/d/qujing/tianzhu/obj/huapao",
"/d/qujing/tianzhu/obj/tiekui",
"/d/qujing/tianzhu/obj/guanpao",
"/d/qujing/tianzhu/obj/baojie",
"/d/qujing/tianzhu/obj/zuanjie",
"/d/qujing/tianzhu/obj/simao",
"/d/qujing/tianzhu/obj/baipao",
"/d/qujing/tianzhu/obj/toujin",
"/d/qujing/tianzhu/obj/fengguan",
"/d/qujing/tianzhu/obj/pimao",
"/d/qujing/tianzhu/obj/piyi",
"/d/qujing/tianzhu/obj/baijie",
"/d/obj/cloth/gongqun",
"/d/qujing/xiaoxitian/obj/shield",
"/d/obj/cloth/jia_sha",
"/d/qujing/yinwu/obj/cloth",
"/d/qujing/zhujie/obj/cloth2",
});	

string *weapon_file = ({
"/d/ourhome/obj/lumber_axe",
"/d/lingtai/obj/bang",
"/d/sea/obj/dragonstick",
"/d/obj/weapon/blade/blade",
"/d/obj/nweapon/sword",
"/d/obj/weapon/spear/huaji2",
"/d/gao/obj/sword",
"/d/sea/obj/dragonspear",
"/d/obj/weapon/sword/changjian",
"/d/obj/weapon/hammer/jiuhulu",
"/d/obj/weapon/whip/fuchen",
"/d/obj/weapon/dagger/dagger",
"/d/obj/weapon/staff/budd_staff",
"/d/city/obj/youping",
"/d/obj/weapon/blade/iceblade",
"/d/obj/weapon/staff/chanzhang",
"/d/obj/weapon/whip/pibian",
"/d/obj/weapon/sword/panguanbi",
"/d/obj/weapon/whip/tielian",
"/d/obj/weapon/hammer/tongchui",
"/d/obj/weapon/whip/whip",
"/d/obj/weapon/sword/qingfeng",
"/d/obj/weapon/stick/wuchangbang",
"/d/obj/weapon/hammer/gucui",
"/obj/npc/obj/golden_sword",
"/d/obj/weapon/sword/qinghong",
"/obj/example/dagger",
"/d/gao/obj/bang",
"/d/obj/weapon/blade/yanblade",
"/d/kaifeng/obj/jiuchipa",
"/d/obj/weapon/hammer/hammer",
"/d/obj/weapon/throwing/dujili",
"/d/gao/obj/blade",
"/d/gao/obj/ruler",
"/d/obj/weapon/stick/mugun",
"/d/obj/weapon/spear/changqiang",
"/d/obj/weapon/spear/tieqiang",
"/d/obj/weapon/spear/jinqiang",
"/d/obj/weapon/mace/goldjian",
"/d/obj/weapon/spear/muqiang",
"/d/obj/weapon/blade/kandao",
"/d/obj/weapon/axe/huafu",
"/d/obj/weapon/mace/malemace",
"/d/obj/weapon/spear/gangqiang",
"/d/obj/weapon/mace/ironmace",
"/d/jjf/obj/lingjian-jian",
"/d/obj/weapon/spear/tiespear",
"/d/jjf/obj/lingjian-qi",
"/d/lingtai/obj/shaoba",
"/d/obj/weapon/stick/bintiegun",
"/d/obj/weapon/stick/qimeigun",
"/d/lingtai/obj/axe",
"/d/obj/weapon/stick/fake-jingubang",
"/d/lingtai/obj/putibang",
"/d/obj/weapon/blade/poshidao",
"/d/meishan/npc/obj/spear",
"/d/obj/weapon/fork/gangcha",
"/d/obj/weapon/mace/copperjian",
"/d/moon/obj/feijian",
"/d/obj/weapon/whip/jueqingwhip",
"/d/moon/obj/daoyaochu",
"/d/moon/obj/bigaxe",
"/d/obj/weapon/sword/snow_sword",
"/d/nanhai/obj/nine-ring",
"/d/nanhai/obj/budd_staff",
"/d/nanhai/obj/tiezhang",
"/d/pansi/obj/yinsuo",
"/d/obj/weapon/whip/longsuo",
"/d/npc/obj/qin",
"/d/penglai/npc/obj/guai",
"/d/penglai/npc/obj/ruyi",
"/d/sea/obj/dragonblade",
"/d/sea/obj/dragonfork",
"/d/sea/obj/dragonstaff",
"/d/sea/obj/dragonrake",
"/d/sea/obj/yincha",
"/d/sea/obj/dragonsword",
"/d/obj/weapon/hammer/bahammer",
"/d/obj/weapon/fork/fork",
"/d/sea/obj/dragonmace",
"/d/obj/weapon/blade/fengdao",
"/d/obj/weapon/whip/snakewhip",
"/d/westway/obj/mabang",
"/d/obj/weapon/throwing/yinzhen",
"/d/obj/weapon/sword/peijian",
"/d/obj/weapon/throwing/kongqueling",
"/d/obj/weapon/blade/xueshandao",
"/d/moon/obj/snow_sword",
"/d/obj/weapon/sword/fenghuangqin",
"/d/obj/weapon/sword/ruler",
"/d/obj/weapon/staff/tieguai",
"/d/obj/weapon/blade/bajiaoshan",
"/d/qujing/wuzhuang/obj/zijinxiao",
"/d/obj/weapon/hammer/baiyuban",
"/d/qujing/baotou/obj/weapon1",
"/d/qujing/baotou/obj/weapon0",
"/d/qujing/baotou/obj/weapon2",
"/d/qujing/baotou/obj/weapon3",
"/d/qujing/baotou/obj/siming",
"/d/qujing/baoxiang/obj/wandao",
"/d/qujing/bibotan/obj/luhua",
"/d/qujing/bibotan/obj/moonstaff",
"/d/qujing/biqiu/obj/staff",
"/d/qujing/biqiu/obj/weapon2",
"/d/qujing/biqiu/obj/weapon3",
"/d/qujing/biqiu/obj/weapon1",
"/d/qujing/chechi/obj/dao",
"/d/qujing/dudi/obj/fork",
"/d/qujing/dudi/obj/cha",
"/d/obj/weapon/blade/jidao",
"/d/obj/weapon/blade/jiedao",
"/d/obj/weapon/spear/huomoqiang",
"/d/sea/obj/dragonwhip",
"/d/qujing/firemount/obj/bian",
"/d/qujing/jilei/obj/weapon0",
"/d/qujing/jilei/obj/weapon3",
"/d/qujing/jilei/obj/weapon1",
"/d/qujing/jilei/obj/weapon6",
"/d/qujing/jilei/obj/weapon2",
"/d/qujing/jilei/obj/weapon4",
"/d/qujing/jilei/obj/weapon5",
"/d/qujing/jilei/obj/wufeng",
"/d/qujing/jindou/obj/weapon1",
"/d/qujing/jindou/obj/weapon2",
"/d/qujing/jindou/obj/weapon0",
"/d/qujing/jindou/obj/weapon3",
"/d/qujing/jindou/obj/qiang",
"/d/qujing/jingjiling/obj/zhang",
"/d/qujing/jingjiling/obj/xingzhi",
"/d/obj/weapon/sword/xijian",
"/d/qujing/pingding/obj/weapon9",
"/d/qujing/pingding/obj/weapon6",
"/d/qujing/pingding/obj/weapon8",
"/d/qujing/pingding/obj/weapon1",
"/d/qujing/pingding/obj/weapon0",
"/d/qujing/pingding/obj/weapon10",
"/d/qujing/pingding/obj/weapon11",
"/d/qujing/tongtian/obj/weapon0",
"/d/qujing/tongtian/obj/weapon2",
"/d/qujing/qilin/obj/weapon11",
"/d/qujing/qilin/obj/weapon12",
"/d/qujing/qilin/obj/weapon10",
"/d/qujing/qilin/obj/weapon20",
"/d/qujing/qilin/obj/weapon22",
"/d/qujing/qilin/obj/weapon21",
"/d/obj/weapon/rake/gangpa",
"/d/obj/weapon/axe/bigaxe",
"/d/qujing/qinfa/obj/dao",
"/d/qujing/qinglong/obj/weapon0",
"/d/qujing/qinglong/obj/weapon4",
"/d/qujing/qinglong/obj/weapon2",
"/d/qujing/qinglong/obj/axe",
"/d/qujing/qinglong/obj/blade",
"/d/qujing/qinglong/obj/stick",
"/d/obj/weapon/blade/wandao",
"/d/obj/weapon/blade/caidao",
"/d/obj/weapon/sword/tiejian",
"/d/obj/weapon/blade/jindao",
"/d/qujing/xiaoxitian/obj/mace",
"/d/qujing/xiaoxitian/obj/weapon6",
"/d/qujing/xiaoxitian/obj/weapon1",
"/d/qujing/xiaoxitian/obj/weapon3",
"/d/qujing/yinwu/obj/weapon0",
"/d/qujing/yinwu/obj/weapon5",
"/d/obj/weapon/axe/tiefu",
"/d/qujing/yinwu/obj/weapon4",
"/d/qujing/yinwu/obj/weapon3",
"/d/qujing/zhujie/obj/weapon21",
"/d/qujing/zhujie/obj/weapon22",
"/d/qujing/zhujie/obj/weapon23",
"/d/qujing/zhujie/obj/weapon20",
});	

string random_msg(string arg)
{
	string *temp,str,*aa,*bb,*cc;
	string rel;
	int i,k,j,type=1;
	if( !arg )
		return 0;
	i = strlen(arg);
	if( is_chinese(arg) )
		type=2;
	aa = ({});
	if( type<2 )
	{
		for(k=0;k<i;k++)
		{
			if( sprintf("%c",arg[k])==" " )
				continue;
			aa+= ({sprintf("%c",arg[k])});
		}
	}
	else
	{
		for(k=0;k<i;k=k+2)
		{
			if( sprintf("%s",arg[j..j+1])==" " )
				continue;
			j = k;
			aa+= ({sprintf("%s",arg[j..j+1])});
		}
	}
	
	temp = aa;
	i = sizeof(aa);
	i = i/2;
	bb = ({});
	rel = this_object()->query_temp("random_rel");
	if( !rel )
	{
		cc = ({
		//	"□","■","×","⊙","∵","∴","∷","█","▓",
		RED,GRN,YEL,BLU,MAG,CYN,WHT,HIR,HIG,HIY,HIB,HIM,
		HIC,HIW,
		});
		//rel = cc[random(sizeof(cc))];
		rel = REV+cc[random(sizeof(cc))]+"  "NOR;
		this_object()->set_temp("random_rel",rel);
	}
	while(i--)
	{
		if( sizeof(temp)<1 )
			break;
		str = temp[random(sizeof(temp))];
		temp-= ({str});
		bb+= ({str});
	}	
	for(i=0;i<sizeof(bb);i++)
	{
		str = bb[i];
		if( str==" " )
			continue;
		arg = replace_string(arg,str,rel);
	}
	return arg;
}	

varargs mapping query_obj_msg(object ob,int no_env)
{
	mapping msg;
	object env,who;
	string name,id,have,where,long,wlong;
	string name2,id2,have2,where2,long2,wlong2;
	if( !ob )
		return 0;
	if( no_env && no_env>1 )
	{
		name2 = COLOR_D->clean_color(ob->query("name"));
		name = random_msg(name2);	
		id2 = ob->query("id");		
		id = random_msg(id2);
		have = have2 = where = where2 = long = long2 = wlong = wlong2 = "";
		msg = ([
			"ture_name" : name2,
			"ture_id"   : id2,
			"ture_t_name" : have2,
			"ture_t_long" : long2,
			"ture_e_short": where2,
			"ture_e_long" : wlong2,
			"obj_name"  : name,
			"obj_id"    : id,
			"who_name"  : have,
			"who_long"  : long,
			"where_name": where,
			"where_long": wlong,
		]);
		return msg;			
	}	
		
	who = environment(ob);
	if( no_env )
	{
		if( !who )
			return 0;
	}
	else
	{			
		if( !who || !living(who) )
			return 0;
	}
	
	if( !no_env )		
	{
		env = environment(who);
		if( !env )
			return 0;
	}

	name2 = COLOR_D->clean_color(ob->query("name"));
	name = random_msg(name2);	
	id2 = ob->query("id");		
	id = random_msg(id2);
	
	if( !no_env )
	{
		have2 = COLOR_D->clean_color(who->short());	
		have = random_msg(COLOR_D->clean_color(who->name()))+"("+random_msg(who->parse_command_id_list()[0])+")";
	}
	else
	{
		if(environment(who)) 
			have2 = COLOR_D->clean_color(MISC_D->find_place(environment(who)));	
		else	
			have2 = COLOR_D->clean_color(MISC_D->find_place(who));	
		have = random_msg(have2);
	}	
	long2 = COLOR_D->clean_color(who->query("long"));
	long = random_msg(long2);
	
	if( !no_env )
	{	
		where2 = COLOR_D->clean_color(MISC_D->find_place(env));
		where = random_msg(where2);
		wlong2 = COLOR_D->clean_color(env->query("long"));
		wlong = random_msg(wlong2);
	}
	else
		where = where2 = wlong = wlong2 = "";	
	
	msg = ([
		"ture_name" : name2,
		"ture_id"   : id2,
		"ture_t_name" : have2,
		"ture_t_long" : long2,
		"ture_e_short": where2,
		"ture_e_long" : wlong2,
		"obj_name"  : name,
		"obj_id"    : id,
		"who_name"  : have,
		"who_long"  : long,
		"where_name": where,
		"where_long": wlong,
	]);
	return msg;
}

void color_counter(object who)
{
    mapping colors=who->query("quest/colors");
    string id=this_object()->query("id");
    string *key;
    string code, *value;
    int i,j;
    
    if(!id || undefinedp(color_code[id])) 
    	return;

    code=color_code[id];
    value=values(color_code);

    if(!colors) 
    {
	    colors=([code: Max_count-1]);
    } 
    else 
    {
	    if(undefinedp(colors[code])) 
	    {
	        colors+=([code: Max_count]);
	    } 
	    else 
	    {
	        colors[code]=Max_count;
	    }
	    key=keys(colors);
	    i=sizeof(key);
	    while(i--) 
	    {
	        if(member_array(key[i],value)==-1) 
	        {
		        map_delete(colors,key[i]);
		        continue;
	        }
	        j=(int)colors[key[i]];
	        if(j>Max_count) j=Max_count;
	        else if(j<=1) 
	        {
		        map_delete(colors,key[i]);
		        continue;
	        }
	        j--;
	        colors[key[i]]=j;
	    }
    }
    who->set("quest/colors",colors);
}

void _quest_done (object who)
{
  string *strs = ({
    "慢慢地一小团"+my_color+"色祥云在$N的身边升起。\n",
    "$N的身上慢慢升起一股"+my_color+"色祥云。\n",
    "一小股"+my_color+"色祥云在$N的身上缓缓升起。\n",
    "只见$N的身上徐徐飘浮起一小团"+my_color+"色祥云。\n",
    "一团"+my_color+"色小祥云在$N的身上慢慢升起。\n",
  });

  if(!who) return;

  message_vision (strs[random(sizeof(strs))],who);
  tell_object (who, "你的品德增加了。\n");
}

void quest_done (object who)
{
  who->add("quest/number",1);
  color_counter(who);
  call_out("_quest_done",1,who);
}

int quest_reward (object who, string quest)
{
  int reward;
  int index = who->query("quest/armor/level");
  int dx = 1000+(index)*(50+random(50));
  
  reward = random(who->query_cps()); // initial value
  reward += dx;
  reward += random(who->query_int())+random(who->query_kar()); // base value
  return reward;
}		